CREATE TABLE [Group] (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_AccountGroup_Id DEFAULT (NEWID()),
    [Name] NVARCHAR(255) NOT NULL,
    [Description] NVARCHAR(4000) NOT NULL,
    [OwnerId] UNIQUEIDENTIFIER NOT NULL,
    [ShowPosition] BIT NOT NULL,

    CONSTRAINT PK_Group PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_Group_AccountHolder FOREIGN KEY ([OwnerId]) REFERENCES [dbo].[User]([Id])
)