// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:5005/' | (string & {});
};

export type Account = {
    utilityType?: UtilityType;
    firstBill?: string | null;
    latestBill?: string | null;
    id: string;
    name: string;
    description?: string | null;
    balanceDate?: string;
    currentBalance: number;
    currentBalanceLocalCurrency: number | null;
    currency: string;
    controller: Controller;
    instrumentType?: string | null;
    groupId?: string | null;
    virtualInstruments?: Array<VirtualInstrument>;
    remainingBalance?: number | null;
    remainingBalanceLocalCurrency?: number | null;
};

export type AccountType = 'NotSet' | 'Transaction' | 'Savings' | 'Credit' | 'Mortgage' | 'Superannuation' | 'Investment' | 'Loan' | 'Broker';

export type AccountTypeSummary = {
    utilityType?: UtilityType;
    from?: string;
    accounts?: Array<string>;
};

export type AllTagAverageReport = {
    tags: Array<TagValue>;
    reportType: ReportType;
    accountId: string;
    start: string;
    end: string;
};

export type Asset = {
    purchasePrice?: number | null;
    shareWithFamily?: boolean;
    id: string;
    name: string;
    description?: string | null;
    balanceDate?: string;
    currentBalance: number;
    currentBalanceLocalCurrency: number | null;
    currency: string;
    controller: Controller;
    instrumentType?: string | null;
    groupId?: string | null;
    virtualInstruments?: Array<VirtualInstrument>;
    remainingBalance?: number | null;
    remainingBalanceLocalCurrency?: number | null;
};

export type Bill = {
    id?: number;
    invoiceNumber?: string | null;
    issueDate?: string;
    currentReading?: number | null;
    previousReading?: number | null;
    total?: number;
    costsIncludeGST?: boolean | null;
    cost?: number;
    periods?: Array<Period>;
    discounts?: Array<Discount>;
};

export type BreakdownReport = {
    tags: Array<TagValue>;
    accountId: string;
    start: string;
    end: string;
};

export type Budget = {
    name?: string | null;
    path?: string | null;
    tags?: string | null;
    authorisationPolicy?: string | null;
};

export type BudgetLine = {
    id?: string;
    name: string;
    tagId?: number;
    notes?: string | null;
    amount?: number;
    month?: number;
    type?: BudgetLineType;
};

export type BudgetLineType = 'Income' | 'Expenses';

export type BudgetReportByMonth = {
    items?: Array<BudgetReportValueMonth>;
};

export type BudgetReportByMonthBreakdown = {
    tags: Array<BudgetReportValueTag>;
};

export type BudgetReportValueMonth = {
    month: number;
    budgetedAmount: number;
    actual: number | null;
};

export type BudgetReportValueTag = {
    name: string;
    budgetedAmount: number;
    actual: number | null;
};

export type ByTagReport = {
    tags: Array<TagValue>;
    accountId: string;
    start: string;
    end: string;
};

export type Controller = 'Manual' | 'Virtual' | 'Import';

export type Create = {
    instrumentId: string;
    bill: CreateBill;
};

export type CreateAccount = {
    name: string;
    description?: string | null;
    importerTypeId?: number | null;
    institutionId: number;
    currency: string;
    balance: number;
    openingDate?: string | null;
    groupId?: string | null;
    accountType?: AccountType;
    controller?: Controller;
    includeInBudget?: boolean;
    shareWithFamily?: boolean;
};

export type CreateAsset = {
    name: string;
    description: string;
    purchasePrice?: number | null;
    currentBalance?: number;
    shareWithFamily: boolean;
    groupId?: string | null;
};

export type CreateBill = {
    invoiceNumber?: string | null;
    issueDate?: string;
    currentReading?: number | null;
    previousReading?: number | null;
    total?: number;
    costsIncludeGST?: boolean | null;
    cost?: number;
    periods?: Array<Period>;
    discounts?: Array<Discount>;
};

export type CreateFamily = {
    name: string;
};

export type CreateGroup = {
    name: string;
    description: string;
    showTotal: boolean;
};

export type CreateInstitution = {
    name: string;
    institutionType: InstitutionType;
};

export type CreateStock = {
    name: string;
    description: string;
    symbol: string;
    price: number;
    quantity: number;
    fees: number;
    shareWithFamily: boolean;
    groupId?: string | null;
};

export type CreateTag = {
    tag: Tag2;
};

export type CreateTransaction = {
    amount: number;
    description: string;
    reference: string | null;
    transactionTime: string;
};

export type CreateVirtualInstrument = {
    name: string;
    description?: string | null;
    openingBalance?: number;
};

export type Discount = {
    discountPercent?: number | null;
    discountAmount?: number | null;
    reason?: string | null;
};

export type Family = {
    id?: string;
    name: string;
    members?: Array<User>;
};

export type Group = {
    id: string;
    name: string;
    description?: string | null;
    showTotal: boolean;
};

export type HexColour = unknown;

export type IFormFile = Blob | File;

export type ImporterType = {
    id?: number;
    type: string;
    name: string;
};

export type InOutReport = {
    income: number;
    outgoings: number;
    accountId: string;
    start: string;
    end: string;
};

export type InOutTrendReport = {
    income: Array<TrendPoint>;
    expenses: Array<unknown>;
    accountId: string;
    start: string;
    end: string;
};

export type Institution = {
    id: number;
    name: string;
    institutionType: InstitutionType;
};

export type InstitutionAccount = {
    id?: string;
    name: string;
    openedDate: string;
    closedDate?: string | null;
    importerTypeId?: number | null;
    institutionId?: number;
};

export type InstitutionType = 'Bank' | 'SuperannuationFund' | 'Broker' | 'CreditUnion' | 'BuildingSociety' | 'InvestmentFund' | 'Government' | 'Other' | 'Utility';

export type Instrument = {
    id: string;
    name: string;
    description?: string | null;
    balanceDate?: string;
    currentBalance: number;
    currentBalanceLocalCurrency: number | null;
    currency: string;
    controller: Controller;
    instrumentType?: string | null;
    groupId?: string | null;
    virtualInstruments?: Array<VirtualInstrument>;
    remainingBalance?: number | null;
    remainingBalanceLocalCurrency?: number | null;
};

export type InstrumentGroup = {
    name: string;
    instruments: Array<Instrument>;
    showTotal?: boolean;
    total?: number | null;
};

export type InstrumentsList = {
    groups: Array<InstrumentGroup>;
    total?: number;
};

export type ListItem = {
    id: string;
    name: string;
};

export type LogicalAccount = {
    accountType?: AccountType;
    isPrimary?: boolean;
    shareWithFamily?: boolean;
    includeInBudget?: boolean;
    institutionAccounts?: Array<InstitutionAccount>;
    lastTransaction?: string | null;
    id: string;
    name: string;
    description?: string | null;
    balanceDate?: string;
    currentBalance: number;
    currentBalanceLocalCurrency: number | null;
    currency: string;
    controller: Controller;
    instrumentType?: string | null;
    groupId?: string | null;
    virtualInstruments?: Array<VirtualInstrument>;
    remainingBalance?: number | null;
    remainingBalanceLocalCurrency?: number | null;
};

export type MonthlyBalancesReport = {
    balances: Array<TrendPoint>;
    accountId: string;
    start: string;
    end: string;
};

export type NullableOfAccountType = 'NotSet' | 'Transaction' | 'Savings' | 'Credit' | 'Mortgage' | 'Superannuation' | 'Investment' | 'Loan' | 'Broker';

export type NullableOfHexColour = unknown;

export type NullableOfTransactionFilterType = 'None' | 'Credit' | 'Debit';

export type Period = {
    periodStart?: string;
    periodEnd?: string;
    daysInclusive?: number;
    days?: number;
    pricePerUnit?: number;
    totalUsage?: number;
    cost?: number;
    chargePerDay?: number;
};

export type RecurringTransaction = {
    id?: string;
    virtualAccountId?: string;
    description?: string | null;
    amount?: number;
    lastRun?: string | null;
    nextRun?: string;
    schedule?: ScheduleFrequency;
};

export type ReportInterval = 'Monthly' | 'Yearly';

export type ReportType = {
    [key: string]: unknown;
};

export type Rule = {
    id: number;
    contains: string;
    description?: string | null;
    tags: Array<Tag>;
};

export type ScheduleFrequency = 'Daily' | 'Weekly' | 'Monthly';

export type SortDirection = 'Ascending' | 'Descending';

export type StockHolding = {
    symbol: string;
    quantity?: number;
    currentPrice?: number;
    currentValue?: number;
    gainLoss?: number;
    shareWithFamily?: boolean;
    id: string;
    name: string;
    description?: string | null;
    balanceDate?: string;
    currentBalance: number;
    currentBalanceLocalCurrency: number | null;
    currency: string;
    controller: Controller;
    instrumentType?: string | null;
    groupId?: string | null;
    virtualInstruments?: Array<VirtualInstrument>;
    remainingBalance?: number | null;
    remainingBalanceLocalCurrency?: number | null;
};

export type StockHoldingReport = {
    accountId?: string;
    currentValue?: number;
    profitLoss?: number;
    adjustedProfitLoss?: number;
};

export type StockTransaction = {
    id?: string;
    accountId?: string;
    price?: number;
    quantity?: number;
    description?: string | null;
    fees?: number;
    accountHolderName?: string | null;
    transactionDate?: string;
    transactionType?: TransactionType;
};

export type StockValueReport = {
    instrumentId: string;
    symbol: string;
    start: string;
    end: string;
    granularity: number;
    points?: Array<StockValueReportPoint>;
    investment?: Array<unknown>;
};

export type StockValueReportPoint = {
    date?: string;
    value?: number;
};

export type Tag = {
    id?: number;
    name: string;
    colour?: NullableOfHexColour;
    tags?: Array<unknown>;
    settings?: TagSettings;
};

export type Tag2 = {
    id?: number;
    name: string;
    colour?: NullableOfHexColour;
    tags?: Array<Tag>;
    settings?: TagSettings;
};

export type TagHierarchy = {
    levels: {
        [key: string]: number;
    };
    tags: Array<Tag>;
};

export type TagSettings = {
    applySmoothing?: boolean;
    excludeFromReporting?: boolean;
};

export type TagTrendReport = {
    tagId: number;
    tagName: string;
    months: Array<TrendPoint>;
    average?: number;
    offsetAverage?: number | null;
    accountId: string;
    start: string;
    end: string;
};

export type TagValue = {
    tagId?: number | null;
    tagName?: string | null;
    grossAmount: number;
    netAmount?: number | null;
    hasChildren?: boolean;
};

export type Transaction = {
    id?: string;
    accountId?: string;
    amount?: number;
    netAmount?: number;
    description?: string | null;
    location?: string | null;
    accountHolderName?: string | null;
    reference?: string | null;
    notes?: string | null;
    excludeFromReporting?: boolean;
    transactionTime?: string;
    purchaseDate?: string | null;
    transactionType?: TransactionType;
    tags?: Array<Tag>;
    splits?: Array<TransactionSplit>;
    offsetFor?: Array<TransactionOffsetFor>;
    extraInfo?: unknown;
};

export type TransactionOffsetBy = {
    transaction: Transaction;
    amount: number;
};

export type TransactionOffsetFor = {
    transaction: Transaction;
    amount: number;
};

export type TransactionSplit = {
    id: string;
    tags: Array<unknown>;
    amount: number;
    offsetBy?: Array<TransactionOffsetBy>;
};

export type TransactionType = 'NotSet' | 'Credit' | 'Debit';

export type TrendPoint = {
    month: string;
    grossAmount: number;
    netAmount?: number | null;
};

export type UpdateFamily = {
    name: string;
};

export type UpdateRule = {
    contains: string;
    description?: string | null;
    tags: Array<Tag>;
};

export type UpdateTag = {
    name: string;
    colour: HexColour;
    excludeFromReporting: boolean;
    applySmoothing: boolean;
};

export type UpdateUser = {
    primaryAccountId?: string | null;
    currency?: string;
    cards?: Array<UserCard>;
};

export type User = {
    id?: string;
    emailAddress: string;
    firstName?: string | null;
    lastName?: string | null;
    currency: string;
    familyId?: string;
    primaryAccountId?: string | null;
    accounts?: Array<string>;
    sharedAccounts?: Array<string>;
};

export type UserCard = {
    id?: string;
    name?: string | null;
    last4Digits: number;
};

export type UserWithCards = {
    cards?: Array<UserCard>;
    id?: string;
    emailAddress: string;
    firstName?: string | null;
    lastName?: string | null;
    currency: string;
    familyId?: string;
    primaryAccountId?: string | null;
    accounts?: Array<string>;
    sharedAccounts?: Array<string>;
};

export type UtilityType = 'Electricity' | 'Gas' | 'Water' | 'Phone' | 'Internet' | 'Other';

export type VirtualInstrument = {
    parentId?: string;
    lastTransaction?: string | null;
    id: string;
    name: string;
    description?: string | null;
    balanceDate?: string;
    currentBalance: number;
    currentBalanceLocalCurrency: number | null;
    currency: string;
    controller: Controller;
    instrumentType?: string | null;
    groupId?: string | null;
    virtualInstruments?: Array<unknown>;
    remainingBalance?: number | null;
    remainingBalanceLocalCurrency?: number | null;
};

export type VirtualInstrument2 = {
    parentId?: string;
    lastTransaction?: string | null;
    id: string;
    name: string;
    description?: string | null;
    balanceDate?: string;
    currentBalance: number;
    currentBalanceLocalCurrency: number | null;
    currency: string;
    controller: Controller;
    instrumentType?: string | null;
    groupId?: string | null;
    virtualInstruments?: Array<VirtualInstrument>;
    remainingBalance?: number | null;
    remainingBalanceLocalCurrency?: number | null;
};

export type GetAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts';
};

export type GetAccountsResponses = {
    /**
     * OK
     */
    200: Array<LogicalAccount>;
};

export type GetAccountsResponse = GetAccountsResponses[keyof GetAccountsResponses];

export type CreateAccountData = {
    body: CreateAccount;
    path?: never;
    query?: never;
    url: '/api/accounts';
};

export type CreateAccountResponses = {
    /**
     * Created
     */
    201: LogicalAccount;
};

export type CreateAccountResponse = CreateAccountResponses[keyof CreateAccountResponses];

export type GetAccountData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}';
};

export type GetAccountResponses = {
    /**
     * OK
     */
    200: LogicalAccount;
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type UpdateAccountData = {
    body: LogicalAccount;
    path?: never;
    query?: never;
    url: '/api/accounts/{id}';
};

export type UpdateAccountResponses = {
    /**
     * OK
     */
    200: LogicalAccount;
};

export type UpdateAccountResponse = UpdateAccountResponses[keyof UpdateAccountResponses];

export type GetAllRecurringTransactionsData = {
    body?: never;
    path: {
        accountId: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/recurring';
};

export type GetAllRecurringTransactionsResponses = {
    /**
     * OK
     */
    200: Array<RecurringTransaction>;
};

export type GetAllRecurringTransactionsResponse = GetAllRecurringTransactionsResponses[keyof GetAllRecurringTransactionsResponses];

export type CreateRecurringTransactionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/{accountId}/recurring';
};

export type CreateRecurringTransactionResponses = {
    /**
     * OK
     */
    200: RecurringTransaction;
    /**
     * Created
     */
    201: RecurringTransaction;
};

export type CreateRecurringTransactionResponse = CreateRecurringTransactionResponses[keyof CreateRecurringTransactionResponses];

export type DeleteRecurringTransactionData = {
    body?: never;
    path: {
        accountId: string;
        recurringTransactionId: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/recurring/{recurringTransactionId}';
};

export type DeleteRecurringTransactionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRecurringTransactionResponse = DeleteRecurringTransactionResponses[keyof DeleteRecurringTransactionResponses];

export type GetRecurringTransactionData = {
    body?: never;
    path: {
        accountId: string;
        recurringTransactionId: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/recurring/{recurringTransactionId}';
};

export type GetRecurringTransactionResponses = {
    /**
     * OK
     */
    200: RecurringTransaction;
};

export type GetRecurringTransactionResponse = GetRecurringTransactionResponses[keyof GetRecurringTransactionResponses];

export type UpdateRecurringTransactionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/{accountId}/recurring/{recurringTransactionId}';
};

export type UpdateRecurringTransactionResponses = {
    /**
     * OK
     */
    200: RecurringTransaction;
};

export type UpdateRecurringTransactionResponse = UpdateRecurringTransactionResponses[keyof UpdateRecurringTransactionResponses];

export type GetRecurringTransactionsForAVirtualAccountData = {
    body?: never;
    path: {
        accountId: string;
        virtualAccountId: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/virtual/{virtualAccountId}/recurring';
};

export type GetRecurringTransactionsForAVirtualAccountResponses = {
    /**
     * OK
     */
    200: Array<RecurringTransaction>;
};

export type GetRecurringTransactionsForAVirtualAccountResponse = GetRecurringTransactionsForAVirtualAccountResponses[keyof GetRecurringTransactionsForAVirtualAccountResponses];

export type GetAssetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/assets/{id}';
};

export type GetAssetResponses = {
    /**
     * OK
     */
    200: Asset;
};

export type GetAssetResponse = GetAssetResponses[keyof GetAssetResponses];

export type UpdateAssetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/assets/{id}';
};

export type UpdateAssetResponses = {
    /**
     * OK
     */
    200: Asset;
};

export type UpdateAssetResponse = UpdateAssetResponses[keyof UpdateAssetResponses];

export type CreateAssetData = {
    body: CreateAsset;
    path?: never;
    query?: never;
    url: '/api/assets';
};

export type CreateAssetResponses = {
    /**
     * Created
     */
    201: Asset;
};

export type CreateAssetResponse = CreateAssetResponses[keyof CreateAssetResponses];

export type GetAllBillsData = {
    body?: never;
    path?: never;
    query: {
        PageSize: number;
        PageNumber: number;
    };
    url: '/api/bills';
};

export type GetAllBillsResponses = {
    /**
     * OK
     */
    200: Bill;
};

export type GetAllBillsResponse = GetAllBillsResponses[keyof GetAllBillsResponses];

export type GetBillAccountSummariesByTypeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bills/accounts/types';
};

export type GetBillAccountSummariesByTypeResponses = {
    /**
     * OK
     */
    200: Array<AccountTypeSummary>;
};

export type GetBillAccountSummariesByTypeResponse = GetBillAccountSummariesByTypeResponses[keyof GetBillAccountSummariesByTypeResponses];

export type GetBillAccountsByTypeData = {
    body?: never;
    path: {
        type: UtilityType;
    };
    query?: never;
    url: '/api/bills/accounts/types/{type}';
};

export type GetBillAccountsByTypeResponses = {
    /**
     * OK
     */
    200: Array<Account>;
};

export type GetBillAccountsByTypeResponse = GetBillAccountsByTypeResponses[keyof GetBillAccountsByTypeResponses];

export type GetBillAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bills/accounts';
};

export type GetBillAccountsResponses = {
    /**
     * OK
     */
    200: Array<Account>;
};

export type GetBillAccountsResponse = GetBillAccountsResponses[keyof GetBillAccountsResponses];

export type GetBillAccountData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/bills/accounts/{instrumentId}';
};

export type GetBillAccountResponses = {
    /**
     * OK
     */
    200: Account;
};

export type GetBillAccountResponse = GetBillAccountResponses[keyof GetBillAccountResponses];

export type GetBillsForAnAccountData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: {
        PageSize?: number;
        PageNumber?: number;
    };
    url: '/api/bills/accounts/{instrumentId}/bills';
};

export type GetBillsForAnAccountResponses = {
    /**
     * OK
     */
    200: Bill;
};

export type GetBillsForAnAccountResponse = GetBillsForAnAccountResponses[keyof GetBillsForAnAccountResponses];

export type CreateBillData = {
    body: Create;
    path?: never;
    query?: never;
    url: '/api/bills/accounts/{instrumentId}/bills';
};

export type CreateBillResponses = {
    /**
     * Created
     */
    201: Bill;
};

export type CreateBillResponse = CreateBillResponses[keyof CreateBillResponses];

export type GetBillData = {
    body?: never;
    path: {
        instrumentId: string;
        id: number;
    };
    query?: never;
    url: '/api/bills/accounts/{instrumentId}/bills/{id}';
};

export type GetBillResponses = {
    /**
     * OK
     */
    200: Bill;
};

export type GetBillResponse = GetBillResponses[keyof GetBillResponses];

export type GetAllBudgetYearsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/budget';
};

export type GetAllBudgetYearsResponses = {
    /**
     * OK
     */
    200: Array<number>;
};

export type GetAllBudgetYearsResponse = GetAllBudgetYearsResponses[keyof GetAllBudgetYearsResponses];

export type GetBudgetData = {
    body?: never;
    path: {
        year: number;
    };
    query?: never;
    url: '/api/budget/{year}';
};

export type GetBudgetResponses = {
    /**
     * OK
     */
    200: Budget;
};

export type GetBudgetResponse = GetBudgetResponses[keyof GetBudgetResponses];

export type DeleteBudgetLineData = {
    body?: never;
    path: {
        year: number;
        id: string;
    };
    query?: never;
    url: '/api/budget/{year}/lines/{id}';
};

export type DeleteBudgetLineResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteBudgetLineResponse = DeleteBudgetLineResponses[keyof DeleteBudgetLineResponses];

export type GetBudgetLineData = {
    body?: never;
    path: {
        year: number;
        id: string;
    };
    query?: never;
    url: '/api/budget/{year}/lines/{id}';
};

export type GetBudgetLineResponses = {
    /**
     * OK
     */
    200: BudgetLine;
};

export type GetBudgetLineResponse = GetBudgetLineResponses[keyof GetBudgetLineResponses];

export type UpdateBudgetLineData = {
    body: BudgetLine;
    path: {
        year: number;
        id: string;
    };
    query?: never;
    url: '/api/budget/{year}/lines/{id}';
};

export type UpdateBudgetLineResponses = {
    /**
     * OK
     */
    200: BudgetLine;
};

export type UpdateBudgetLineResponse = UpdateBudgetLineResponses[keyof UpdateBudgetLineResponses];

export type CreateBudgetLineData = {
    body: BudgetLine;
    path: {
        year: number;
    };
    query?: never;
    url: '/api/budget/{year}/lines';
};

export type CreateBudgetLineResponses = {
    /**
     * OK
     */
    200: BudgetLine;
    /**
     * Created
     */
    201: BudgetLine;
};

export type CreateBudgetLineResponse = CreateBudgetLineResponses[keyof CreateBudgetLineResponses];

export type GetBudgetAmountForTagData = {
    body?: never;
    path: {
        tagId: number;
    };
    query?: never;
    url: '/api/budget/tag/{tagId}';
};

export type GetBudgetAmountForTagResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetBudgetAmountForTagResponse = GetBudgetAmountForTagResponses[keyof GetBudgetAmountForTagResponses];

export type GetBudgetReportData = {
    body?: never;
    path: {
        year: number;
    };
    query?: never;
    url: '/api/budget/{year}/report';
};

export type GetBudgetReportResponses = {
    /**
     * OK
     */
    200: BudgetReportByMonth;
};

export type GetBudgetReportResponse = GetBudgetReportResponses[keyof GetBudgetReportResponses];

export type GetBudgetReportForMonthData = {
    body?: never;
    path: {
        year: number;
        month: number;
    };
    query?: never;
    url: '/api/budget/{year}/report/{month}';
};

export type GetBudgetReportForMonthResponses = {
    /**
     * OK
     */
    200: BudgetReportValueMonth;
};

export type GetBudgetReportForMonthResponse = GetBudgetReportForMonthResponses[keyof GetBudgetReportForMonthResponses];

export type GetBudgetReportBreakdownForMonthData = {
    body?: never;
    path: {
        year: number;
        month: number;
    };
    query?: never;
    url: '/api/budget/{year}/report/{month}/breakdown';
};

export type GetBudgetReportBreakdownForMonthResponses = {
    /**
     * OK
     */
    200: BudgetReportByMonthBreakdown;
};

export type GetBudgetReportBreakdownForMonthResponse = GetBudgetReportBreakdownForMonthResponses[keyof GetBudgetReportBreakdownForMonthResponses];

export type GetBudgetReportBreakdownForMonthForUnbudgetedItemsData = {
    body?: never;
    path: {
        year: number;
        month: number;
    };
    query?: never;
    url: '/api/budget/{year}/report/{month}/breakdown/unbudgeted';
};

export type GetBudgetReportBreakdownForMonthForUnbudgetedItemsResponses = {
    /**
     * OK
     */
    200: BudgetReportByMonthBreakdown;
};

export type GetBudgetReportBreakdownForMonthForUnbudgetedItemsResponse = GetBudgetReportBreakdownForMonthForUnbudgetedItemsResponses[keyof GetBudgetReportBreakdownForMonthForUnbudgetedItemsResponses];

export type GetAllFamiliesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/families';
};

export type GetAllFamiliesResponses = {
    /**
     * OK
     */
    200: Array<Family>;
};

export type GetAllFamiliesResponse = GetAllFamiliesResponses[keyof GetAllFamiliesResponses];

export type CreateFamilyData = {
    body: CreateFamily;
    path?: never;
    query?: never;
    url: '/api/families';
};

export type CreateFamilyResponses = {
    /**
     * Created
     */
    201: Family;
};

export type CreateFamilyResponse = CreateFamilyResponses[keyof CreateFamilyResponses];

export type GetFamilyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/families/{id}';
};

export type GetFamilyResponses = {
    /**
     * OK
     */
    200: Family;
};

export type GetFamilyResponse = GetFamilyResponses[keyof GetFamilyResponses];

export type UpdateFamilyData = {
    body: UpdateFamily;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/families/{id}';
};

export type UpdateFamilyResponses = {
    /**
     * OK
     */
    200: Family;
};

export type UpdateFamilyResponse = UpdateFamilyResponses[keyof UpdateFamilyResponses];

export type GetAllGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/groups';
};

export type GetAllGroupsResponses = {
    /**
     * OK
     */
    200: Array<Group>;
};

export type GetAllGroupsResponse = GetAllGroupsResponses[keyof GetAllGroupsResponses];

export type CreateGroupData = {
    body: CreateGroup;
    path?: never;
    query?: never;
    url: '/api/groups';
};

export type CreateGroupResponses = {
    /**
     * OK
     */
    200: Group;
    /**
     * Created
     */
    201: Group;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type DeleteGroupData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type DeleteGroupResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type GetGroupData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type GetGroupResponses = {
    /**
     * OK
     */
    200: Group;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type UpdateGroupData = {
    body: Group;
    path?: never;
    query?: never;
    url: '/api/groups/{id}';
};

export type UpdateGroupResponses = {
    /**
     * OK
     */
    200: Group;
};

export type UpdateGroupResponse = UpdateGroupResponses[keyof UpdateGroupResponses];

export type GetAllInstitutionsData = {
    body?: never;
    path?: never;
    query?: {
        AccountType?: NullableOfAccountType;
    };
    url: '/api/institutions';
};

export type GetAllInstitutionsResponses = {
    /**
     * OK
     */
    200: Array<Institution>;
};

export type GetAllInstitutionsResponse = GetAllInstitutionsResponses[keyof GetAllInstitutionsResponses];

export type CreateInstitutionData = {
    body: CreateInstitution;
    path?: never;
    query?: never;
    url: '/api/institutions';
};

export type CreateInstitutionResponses = {
    /**
     * Created
     */
    201: Institution;
};

export type CreateInstitutionResponse = CreateInstitutionResponses[keyof CreateInstitutionResponses];

export type GetInstitutionData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/institutions/{id}';
};

export type GetInstitutionResponses = {
    /**
     * OK
     */
    200: Institution;
};

export type GetInstitutionResponse = GetInstitutionResponses[keyof GetInstitutionResponses];

export type UpdateInstitutionData = {
    body?: never;
    path: {
        id: number;
    };
    query: {
        Name: string;
        InstitutionType: InstitutionType;
    };
    url: '/api/institutions/{id}';
};

export type UpdateInstitutionResponses = {
    /**
     * OK
     */
    200: Institution;
};

export type UpdateInstitutionResponse = UpdateInstitutionResponses[keyof UpdateInstitutionResponses];

export type GetFormattedInstrumentsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/instruments/summary';
};

export type GetFormattedInstrumentsListResponses = {
    /**
     * OK
     */
    200: InstrumentsList;
};

export type GetFormattedInstrumentsListResponse = GetFormattedInstrumentsListResponses[keyof GetFormattedInstrumentsListResponses];

export type GetInstrumentsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/instruments/list';
};

export type GetInstrumentsListResponses = {
    /**
     * OK
     */
    200: Array<ListItem>;
};

export type GetInstrumentsListResponse = GetInstrumentsListResponses[keyof GetInstrumentsListResponses];

export type ImportData = {
    body: {
        file: IFormFile;
    };
    path: {
        instrumentId: string;
        accountId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/accounts/{accountId}/import';
};

export type ImportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReprocessData = {
    body?: never;
    path: {
        instrumentId: string;
        accountId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/accounts/{accountId}/import/reprocess';
};

export type ReprocessResponses = {
    /**
     * No Content
     */
    204: void;
};

export type ReprocessResponse = ReprocessResponses[keyof ReprocessResponses];

export type GetAllInstrumentRulesData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules';
};

export type GetAllInstrumentRulesResponses = {
    /**
     * OK
     */
    200: Array<Rule>;
};

export type GetAllInstrumentRulesResponse = GetAllInstrumentRulesResponses[keyof GetAllInstrumentRulesResponses];

export type CreateInstrumentRuleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/instruments/{instrumentId}/rules';
};

export type CreateInstrumentRuleResponses = {
    /**
     * OK
     */
    200: Rule;
    /**
     * Created
     */
    201: Rule;
};

export type CreateInstrumentRuleResponse = CreateInstrumentRuleResponses[keyof CreateInstrumentRuleResponses];

export type DeleteInstrumentRuleData = {
    body?: never;
    path: {
        instrumentId: string;
        ruleId: number;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules/{ruleId}';
};

export type DeleteInstrumentRuleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteInstrumentRuleResponse = DeleteInstrumentRuleResponses[keyof DeleteInstrumentRuleResponses];

export type GetInstrumentRuleData = {
    body?: never;
    path: {
        instrumentId: string;
        ruleId: number;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules/{ruleId}';
};

export type GetInstrumentRuleResponses = {
    /**
     * OK
     */
    200: Rule;
};

export type GetInstrumentRuleResponse = GetInstrumentRuleResponses[keyof GetInstrumentRuleResponses];

export type UpdateInstrumentRuleData = {
    body: UpdateRule;
    path: {
        instrumentId: string;
        ruleId: number;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules/{ruleId}';
};

export type UpdateInstrumentRuleResponses = {
    /**
     * OK
     */
    200: Rule;
};

export type UpdateInstrumentRuleResponse = UpdateInstrumentRuleResponses[keyof UpdateInstrumentRuleResponses];

export type RemoveTagFromInstrumentRuleData = {
    body?: never;
    path: {
        instrumentId: string;
        ruleId: number;
        tagId: number;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules/{ruleId}/tag/{tagId}';
};

export type RemoveTagFromInstrumentRuleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveTagFromInstrumentRuleResponse = RemoveTagFromInstrumentRuleResponses[keyof RemoveTagFromInstrumentRuleResponses];

export type AddTagToInstrumentRuleData = {
    body?: never;
    path: {
        instrumentId: string;
        ruleId: number;
        tagId: number;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules/{ruleId}/tag/{tagId}';
};

export type AddTagToInstrumentRuleResponses = {
    /**
     * OK
     */
    200: Rule;
};

export type AddTagToInstrumentRuleResponse = AddTagToInstrumentRuleResponses[keyof AddTagToInstrumentRuleResponses];

export type RunRulesData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules/run';
};

export type RunRulesResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetVirtualInstrumentsData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/virtual';
};

export type GetVirtualInstrumentsResponses = {
    /**
     * OK
     */
    200: Array<VirtualInstrument>;
};

export type GetVirtualInstrumentsResponse = GetVirtualInstrumentsResponses[keyof GetVirtualInstrumentsResponses];

export type CreateVirtualInstrumentData = {
    body: CreateVirtualInstrument;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/virtual';
};

export type CreateVirtualInstrumentResponses = {
    /**
     * Created
     */
    201: VirtualInstrument2;
};

export type CreateVirtualInstrumentResponse = CreateVirtualInstrumentResponses[keyof CreateVirtualInstrumentResponses];

export type DeleteVirtualInstrumentData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query: {
        VirtualAccountId: string;
    };
    url: '/api/instruments/{instrumentId}/virtual/{virtualInstrumentId}';
};

export type DeleteVirtualInstrumentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteVirtualInstrumentResponse = DeleteVirtualInstrumentResponses[keyof DeleteVirtualInstrumentResponses];

export type GetVirtualInstrumentData = {
    body?: never;
    path: {
        instrumentId: string;
        virtualInstrumentId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/virtual/{virtualInstrumentId}';
};

export type GetVirtualInstrumentResponses = {
    /**
     * OK
     */
    200: VirtualInstrument2;
};

export type GetVirtualInstrumentResponse = GetVirtualInstrumentResponses[keyof GetVirtualInstrumentResponses];

export type UpdateVirtualInstrumentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/instruments/{instrumentId}/virtual/{virtualInstrumentId}';
};

export type UpdateVirtualInstrumentResponses = {
    /**
     * OK
     */
    200: VirtualInstrument2;
};

export type UpdateVirtualInstrumentResponse = UpdateVirtualInstrumentResponses[keyof UpdateVirtualInstrumentResponses];

export type ImporterTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/reference-data/importer-types';
};

export type ImporterTypesResponses = {
    /**
     * OK
     */
    200: Array<ImporterType>;
};

export type ImporterTypesResponse = ImporterTypesResponses[keyof ImporterTypesResponses];

export type InOutReportData = {
    body?: never;
    path: {
        accountId: string;
        start: string;
        end: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/reports/in-out/{start}/{end}';
};

export type InOutReportResponses = {
    /**
     * OK
     */
    200: InOutReport;
};

export type InOutReportResponse = InOutReportResponses[keyof InOutReportResponses];

export type InOutTrendReportData = {
    body?: never;
    path: {
        accountId: string;
        start: string;
        end: string;
    };
    query: {
        Interval: ReportInterval;
    };
    url: '/api/accounts/{accountId}/reports/in-out-trend/{start}/{end}';
};

export type InOutTrendReportResponses = {
    /**
     * OK
     */
    200: InOutTrendReport;
};

export type InOutTrendReportResponse = InOutTrendReportResponses[keyof InOutTrendReportResponses];

export type InOutAverageReportData = {
    body?: never;
    path: {
        accountId: string;
        start: string;
        end: string;
    };
    query: {
        Interval: ReportInterval;
    };
    url: '/api/accounts/{accountId}/reports/in-out-average/{start}/{end}';
};

export type InOutAverageReportResponses = {
    /**
     * OK
     */
    200: InOutReport;
};

export type InOutAverageReportResponse = InOutAverageReportResponses[keyof InOutAverageReportResponses];

export type ByTagReportData = {
    body?: never;
    path: {
        parentTagId: number;
        reportType: ReportType;
        accountId: string;
        start: string;
        end: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/reports/{reportType}/tags/{start}/{end}/{parentTagId}';
};

export type ByTagReportResponses = {
    /**
     * OK
     */
    200: ByTagReport;
};

export type ByTagReportResponse = ByTagReportResponses[keyof ByTagReportResponses];

export type TagBreakdownReportData = {
    body?: never;
    path: {
        parentTagId: number;
        reportType: ReportType;
        accountId: string;
        start: string;
        end: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/reports/{reportType}/breakdown/{start}/{end}/{parentTagId}';
};

export type TagBreakdownReportResponses = {
    /**
     * OK
     */
    200: BreakdownReport;
};

export type TagBreakdownReportResponse = TagBreakdownReportResponses[keyof TagBreakdownReportResponses];

export type TagTrendReportData = {
    body?: never;
    path: {
        tagId: number;
        reportType: ReportType;
        accountId: string;
        start: string;
        end: string;
    };
    query?: {
        ApplySmoothing?: boolean;
    };
    url: '/api/accounts/{accountId}/reports/{reportType}/tag-trend/{start}/{end}/{tagId}';
};

export type TagTrendReportResponses = {
    /**
     * OK
     */
    200: TagTrendReport;
};

export type TagTrendReportResponse = TagTrendReportResponses[keyof TagTrendReportResponses];

export type AllTagAverageReportData = {
    body?: never;
    path: {
        reportType: ReportType;
        accountId: string;
        start: string;
        end: string;
    };
    query: {
        Top: number;
        Interval: ReportInterval;
    };
    url: '/api/accounts/{accountId}/reports/{reportType}/all-tag-average/{start}/{end}';
};

export type AllTagAverageReportResponses = {
    /**
     * OK
     */
    200: AllTagAverageReport;
};

export type AllTagAverageReportResponse = AllTagAverageReportResponses[keyof AllTagAverageReportResponses];

export type MonthlyBalancesReportData = {
    body?: never;
    path: {
        accountId: string;
        start: string;
        end: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/reports/monthly-balances/{start}/{end}';
};

export type MonthlyBalancesReportResponses = {
    /**
     * OK
     */
    200: MonthlyBalancesReport;
};

export type MonthlyBalancesReportResponse = MonthlyBalancesReportResponses[keyof MonthlyBalancesReportResponses];

export type GetStockHoldingData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/stocks/{instrumentId}';
};

export type GetStockHoldingResponses = {
    /**
     * OK
     */
    200: StockHolding;
};

export type GetStockHoldingResponse = GetStockHoldingResponses[keyof GetStockHoldingResponses];

export type UpdateStockHoldingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/stocks/{instrumentId}';
};

export type UpdateStockHoldingResponses = {
    /**
     * OK
     */
    200: StockHolding;
};

export type UpdateStockHoldingResponse = UpdateStockHoldingResponses[keyof UpdateStockHoldingResponses];

export type GetStockHoldingCpiAdjustedGainLossData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/stocks/{instrumentId}/cpi-adjusted-gain-loss';
};

export type GetStockHoldingCpiAdjustedGainLossResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetStockHoldingCpiAdjustedGainLossResponse = GetStockHoldingCpiAdjustedGainLossResponses[keyof GetStockHoldingCpiAdjustedGainLossResponses];

export type CreateStockHoldingData = {
    body: CreateStock;
    path?: never;
    query?: never;
    url: '/api/stocks';
};

export type CreateStockHoldingResponses = {
    /**
     * Created
     */
    201: StockHolding;
};

export type CreateStockHoldingResponse = CreateStockHoldingResponses[keyof CreateStockHoldingResponses];

export type StockHoldingReportData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/stocks/{instrumentId}/reports/holding';
};

export type StockHoldingReportResponses = {
    /**
     * OK
     */
    200: StockHoldingReport;
};

export type StockHoldingReportResponse = StockHoldingReportResponses[keyof StockHoldingReportResponses];

export type StockValueReportData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query: {
        Start: string;
        End: string;
    };
    url: '/api/stocks/{instrumentId}/reports/value';
};

export type StockValueReportResponses = {
    /**
     * OK
     */
    200: StockValueReport;
};

export type StockValueReportResponse = StockValueReportResponses[keyof StockValueReportResponses];

export type GetStockTransactionsData = {
    body?: never;
    path: {
        instrumentId: string;
        pageSize: number;
        pageNumber: number;
    };
    query: {
        Filter?: string;
        Start?: string;
        End?: string;
        SortField?: string;
        SortDirection: SortDirection;
    };
    url: '/api/stocks/{instrumentId}/transactions/{pageSize}/{pageNumber}';
};

export type GetStockTransactionsResponses = {
    /**
     * OK
     */
    200: StockTransaction;
};

export type GetStockTransactionsResponse = GetStockTransactionsResponses[keyof GetStockTransactionsResponses];

export type CreateStockTransactionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/stocks/{instrumentId}/transactions';
};

export type CreateStockTransactionResponses = {
    /**
     * OK
     */
    200: StockTransaction;
};

export type CreateStockTransactionResponse = CreateStockTransactionResponses[keyof CreateStockTransactionResponses];

export type GetTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tags';
};

export type GetTagsResponses = {
    /**
     * OK
     */
    200: Array<Tag>;
};

export type GetTagsResponse = GetTagsResponses[keyof GetTagsResponses];

export type CreateTagData = {
    body: CreateTag;
    path?: never;
    query?: never;
    url: '/api/tags';
};

export type CreateTagResponses = {
    /**
     * Created
     */
    201: Tag2;
};

export type CreateTagResponse = CreateTagResponses[keyof CreateTagResponses];

export type GetTagHierarchyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tags/hierarchy';
};

export type GetTagHierarchyResponses = {
    /**
     * OK
     */
    200: TagHierarchy;
};

export type GetTagHierarchyResponse = GetTagHierarchyResponses[keyof GetTagHierarchyResponses];

export type DeleteTagData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tags/{id}';
};

export type DeleteTagResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type GetTagData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tags/{id}';
};

export type GetTagResponses = {
    /**
     * OK
     */
    200: Tag2;
};

export type GetTagResponse = GetTagResponses[keyof GetTagResponses];

export type UpdateTagData = {
    body: UpdateTag;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tags/{id}';
};

export type UpdateTagResponses = {
    /**
     * OK
     */
    200: Tag2;
};

export type UpdateTagResponse = UpdateTagResponses[keyof UpdateTagResponses];

export type CreateTagByNameData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tags/{name}';
};

export type CreateTagByNameResponses = {
    /**
     * Created
     */
    201: Tag2;
};

export type CreateTagByNameResponse = CreateTagByNameResponses[keyof CreateTagByNameResponses];

export type RemoveSubTagData = {
    body?: never;
    path: {
        id: number;
        subTagId: number;
    };
    query?: never;
    url: '/api/tags/{id}/tags/{subTagId}';
};

export type RemoveSubTagResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveSubTagResponse = RemoveSubTagResponses[keyof RemoveSubTagResponses];

export type AddSubTagData = {
    body?: never;
    path: {
        id: number;
        subTagId: number;
    };
    query?: never;
    url: '/api/tags/{id}/tags/{subTagId}';
};

export type AddSubTagResponses = {
    /**
     * OK
     */
    200: Tag2;
};

export type AddSubTagResponse = AddSubTagResponses[keyof AddSubTagResponses];

export type GetTransactionsData = {
    body?: never;
    path: {
        pageSize: number;
        pageNumber: number;
        instrumentId: string;
    };
    query: {
        Filter?: string;
        Start?: string;
        End?: string;
        TagIds?: Array<number>;
        SortField?: string;
        TransactionType?: NullableOfTransactionFilterType;
        SortDirection: SortDirection;
        Untagged?: string;
        ExcludeNetZero?: boolean;
    };
    url: '/api/accounts/{instrumentId}/transactions/{pageSize}/{pageNumber}';
};

export type GetTransactionsResponses = {
    /**
     * OK
     */
    200: Transaction;
};

export type GetTransactionsResponse = GetTransactionsResponses[keyof GetTransactionsResponses];

export type GetUntaggedTransactionsData = {
    body?: never;
    path: {
        pageSize: number;
        pageNumber: number;
        instrumentId: string;
        untagged: string;
    };
    query: {
        Filter?: string;
        Start?: string;
        End?: string;
        TagIds?: Array<number>;
        SortField?: string;
        TransactionType?: NullableOfTransactionFilterType;
        SortDirection: SortDirection;
        ExcludeNetZero?: boolean;
    };
    url: '/api/accounts/{instrumentId}/transactions/{untagged}/{pageSize}/{pageNumber}';
};

export type GetUntaggedTransactionsResponses = {
    /**
     * OK
     */
    200: Transaction;
};

export type GetUntaggedTransactionsResponse = GetUntaggedTransactionsResponses[keyof GetUntaggedTransactionsResponses];

export type SearchTransactionsData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query: {
        Start: string;
        TransactionType: TransactionType;
        TagIds: Array<number>;
    };
    url: '/api/accounts/{instrumentId}/transactions';
};

export type SearchTransactionsResponses = {
    /**
     * OK
     */
    200: Array<Transaction>;
};

export type SearchTransactionsResponse = SearchTransactionsResponses[keyof SearchTransactionsResponses];

export type CreateTransactionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/{instrumentId}/transactions';
};

export type CreateTransactionResponses = {
    /**
     * OK
     */
    200: Transaction;
};

export type CreateTransactionResponse = CreateTransactionResponses[keyof CreateTransactionResponses];

export type SetBalanceData = {
    body: CreateTransaction;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}/transactions/balance-adjustment';
};

export type SetBalanceResponses = {
    /**
     * OK
     */
    200: Transaction;
};

export type SetBalanceResponse = SetBalanceResponses[keyof SetBalanceResponses];

export type UpdateTransactionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/{instrumentId}/transactions/{id}';
};

export type UpdateTransactionResponses = {
    /**
     * OK
     */
    200: Transaction;
};

export type UpdateTransactionResponse = UpdateTransactionResponses[keyof UpdateTransactionResponses];

export type RemoveTagData = {
    body?: never;
    path: {
        instrumentId: string;
        id: string;
        tagId: number;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}/transactions/{id}/tag/{tagId}';
};

export type RemoveTagResponses = {
    /**
     * OK
     */
    200: Transaction;
};

export type RemoveTagResponse = RemoveTagResponses[keyof RemoveTagResponses];

export type AddTagData = {
    body?: never;
    path: {
        instrumentId: string;
        id: string;
        tagId: number;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}/transactions/{id}/tag/{tagId}';
};

export type AddTagResponses = {
    /**
     * OK
     */
    200: Transaction;
};

export type AddTagResponse = AddTagResponses[keyof AddTagResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetUserResponses = {
    /**
     * OK
     */
    200: UserWithCards;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UpdateUser;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: UserWithCards;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];
