import { ComboBox, ComboBoxProps } from "@andrewmclachlan/mooapp";

type Currency = { name: string, code: string };

interface CurrencySelectorProps extends Omit<ComboBoxProps<Currency>, "value" | "onChange" | "valueField" | "labelField"> {
    value: string;
    onChange: (value: string) => void;
}

export const CurrencySelector: React.FC<CurrencySelectorProps> = ({ value, onChange, ref, ...props }) => {

    const currency = value ? [currencies.find(c => c.code === value)] : undefined;

    return (
        <ComboBox onChange={(c: Currency[]) => onChange(currency[0].code)} selectedItems={currency} items={currencies} valueField={o => o.code} labelField={o => `${o?.name} (${o?.code})`} {...props} ref={ref}  />
    );
};

CurrencySelector.displayName = "CurrencySelector";

const currencies: Currency[] = [
    { name: "UAE Dirham", code: "AED", },
    { name: "Afghani", code: "AFN", },
    { name: "Lek", code: "ALL", },
    { name: "Armenian Dram", code: "AMD", },
    { name: "Netherlands Antillean Guilder", code: "ANG", },
    { name: "Kwanza", code: "AOA", },
    { name: "Argentine Peso", code: "ARS", },
    { name: "Australian Dollar", code: "AUD", },
    { name: "Aruban Florin", code: "AWG", },
    { name: "Azerbaijan Manat", code: "AZN", },
    { name: "Convertible Mark", code: "BAM", },
    { name: "Barbados Dollar", code: "BBD", },
    { name: "Taka", code: "BDT", },
    { name: "Bulgarian Lev", code: "BGN", },
    { name: "Bahraini Dinar", code: "BHD", },
    { name: "Burundi Franc", code: "BIF", },
    { name: "Bermudian Dollar", code: "BMD", },
    { name: "Brunei Dollar", code: "BND", },
    { name: "Boliviano", code: "BOB", },
    { name: "Mvdol", code: "BOV", },
    { name: "Brazilian Real", code: "BRL", },
    { name: "Bahamian Dollar", code: "BSD", },
    { name: "Ngultrum", code: "BTN", },
    { name: "Pula", code: "BWP", },
    { name: "Belarusian Ruble", code: "BYN", },
    { name: "Belize Dollar", code: "BZD", },
    { name: "Canadian Dollar", code: "CAD", },
    { name: "Congolese Franc", code: "CDF", },
    { name: "WIR Euro", code: "CHE", },
    { name: "Swiss Franc", code: "CHF", },
    { name: "WIR Franc", code: "CHW", },
    { name: "Unidad de Fomento", code: "CLF", },
    { name: "Chilean Peso", code: "CLP", },
    { name: "Yuan Renminbi", code: "CNY", },
    { name: "Colombian Peso", code: "COP", },
    { name: "Unidad de Valor Real", code: "COU", },
    { name: "Costa Rican Colon", code: "CRC", },
    { name: "Peso Convertible", code: "CUC", },
    { name: "Cuban Peso", code: "CUP", },
    { name: "Cabo Verde Escudo", code: "CVE", },
    { name: "Czech Koruna", code: "CZK", },
    { name: "Djibouti Franc", code: "DJF", },
    { name: "Danish Krone", code: "DKK", },
    { name: "Dominican Peso", code: "DOP", },
    { name: "Algerian Dinar", code: "DZD", },
    { name: "Egyptian Pound", code: "EGP", },
    { name: "Nakfa", code: "ERN", },
    { name: "Ethiopian Birr", code: "ETB", },
    { name: "Euro", code: "EUR", },
    { name: "Fiji Dollar", code: "FJD", },
    { name: "Falkland Islands Pound", code: "FKP", },
    { name: "Pound Sterling", code: "GBP", },
    { name: "Lari", code: "GEL", },
    { name: "Ghana Cedi", code: "GHS", },
    { name: "Gibraltar Pound", code: "GIP", },
    { name: "Dalasi", code: "GMD", },
    { name: "Guinean Franc", code: "GNF", },
    { name: "Quetzal", code: "GTQ", },
    { name: "Guyana Dollar", code: "GYD", },
    { name: "Hong Kong Dollar", code: "HKD", },
    { name: "Lempira", code: "HNL", },
    { name: "Kuna", code: "HRK", },
    { name: "Gourde", code: "HTG", },
    { name: "Forint", code: "HUF", },
    { name: "Rupiah", code: "IDR", },
    { name: "New Israeli Sheqel", code: "ILS", },
    { name: "Indian Rupee", code: "INR", },
    { name: "Iraqi Dinar", code: "IQD", },
    { name: "Iranian Rial", code: "IRR", },
    { name: "Iceland Krona", code: "ISK", },
    { name: "Jamaican Dollar", code: "JMD", },
    { name: "Jordanian Dinar", code: "JOD", },
    { name: "Yen", code: "JPY", },
    { name: "Kenyan Shilling", code: "KES", },
    { name: "Som", code: "KGS", },
    { name: "Riel", code: "KHR", },
    { name: "Comorian Franc ", code: "KMF", },
    { name: "North Korean Won", code: "KPW", },
    { name: "Won", code: "KRW", },
    { name: "Kuwaiti Dinar", code: "KWD", },
    { name: "Cayman Islands Dollar", code: "KYD", },
    { name: "Tenge", code: "KZT", },
    { name: "Lao Kip", code: "LAK", },
    { name: "Lebanese Pound", code: "LBP", },
    { name: "Sri Lanka Rupee", code: "LKR", },
    { name: "Liberian Dollar", code: "LRD", },
    { name: "Loti", code: "LSL", },
    { name: "Libyan Dinar", code: "LYD", },
    { name: "Moroccan Dirham", code: "MAD", },
    { name: "Moldovan Leu", code: "MDL", },
    { name: "Malagasy Ariary", code: "MGA", },
    { name: "Denar", code: "MKD", },
    { name: "Kyat", code: "MMK", },
    { name: "Tugrik", code: "MNT", },
    { name: "Pataca", code: "MOP", },
    { name: "Ouguiya", code: "MRU", },
    { name: "Mauritius Rupee", code: "MUR", },
    { name: "Rufiyaa", code: "MVR", },
    { name: "Malawi Kwacha", code: "MWK", },
    { name: "Mexican Peso", code: "MXN", },
    { name: "Mexican Unidad de Inversion (UDI)", code: "MXV", },
    { name: "Malaysian Ringgit", code: "MYR", },
    { name: "Mozambique Metical", code: "MZN", },
    { name: "Namibia Dollar", code: "NAD", },
    { name: "Naira", code: "NGN", },
    { name: "Cordoba Oro", code: "NIO", },
    { name: "Norwegian Krone", code: "NOK", },
    { name: "Nepalese Rupee", code: "NPR", },
    { name: "New Zealand Dollar", code: "NZD", },
    { name: "Rial Omani", code: "OMR", },
    { name: "Balboa", code: "PAB", },
    { name: "Sol", code: "PEN", },
    { name: "Kina", code: "PGK", },
    { name: "Philippine Peso", code: "PHP", },
    { name: "Pakistan Rupee", code: "PKR", },
    { name: "Zloty", code: "PLN", },
    { name: "Guarani", code: "PYG", },
    { name: "Qatari Rial", code: "QAR", },
    { name: "Romanian Leu", code: "RON", },
    { name: "Serbian Dinar", code: "RSD", },
    { name: "Russian Ruble", code: "RUB", },
    { name: "Rwanda Franc", code: "RWF", },
    { name: "Saudi Riyal", code: "SAR", },
    { name: "Solomon Islands Dollar", code: "SBD", },
    { name: "Seychelles Rupee", code: "SCR", },
    { name: "Sudanese Pound", code: "SDG", },
    { name: "Swedish Krona", code: "SEK", },
    { name: "Singapore Dollar", code: "SGD", },
    { name: "Saint Helena Pound", code: "SHP", },
    { name: "Leone", code: "SLL", },
    { name: "Somali Shilling", code: "SOS", },
    { name: "Surinam Dollar", code: "SRD", },
    { name: "South Sudanese Pound", code: "SSP", },
    { name: "Dobra", code: "STN", },
    { name: "El Salvador Colon", code: "SVC", },
    { name: "Syrian Pound", code: "SYP", },
    { name: "Lilangeni", code: "SZL", },
    { name: "Baht", code: "THB", },
    { name: "Somoni", code: "TJS", },
    { name: "Turkmenistan New Manat", code: "TMT", },
    { name: "Tunisian Dinar", code: "TND", },
    { name: "Pa'anga", code: "TOP", },
    { name: "Turkish Lira", code: "TRY", },
    { name: "Trinidad and Tobago Dollar", code: "TTD", },
    { name: "New Taiwan Dollar", code: "TWD", },
    { name: "Tanzanian Shilling", code: "TZS", },
    { name: "Hryvnia", code: "UAH", },
    { name: "Uganda Shilling", code: "UGX", },
    { name: "US Dollar", code: "USD", },
    { name: "US Dollar (Next day)", code: "USN", },
    { name: "Uruguay Peso en Unidades Indexadas (UI)", code: "UYI", },
    { name: "Peso Uruguayo", code: "UYU", },
    { name: "Unidad Previsional", code: "UYW", },
    { name: "Uzbekistan Sum", code: "UZS", },
    { name: "BolÃ­var Soberano", code: "VES", },
    { name: "Dong", code: "VND", },
    { name: "Vatu", code: "VUV", },
    { name: "Tala", code: "WST", },
    { name: "CFA Franc BEAC", code: "XAF", },
    { name: "Silver", code: "XAG", },
    { name: "Gold", code: "XAU", },
    { name: "Bond Markets Unit European Composite Unit (EURCO)", code: "XBA", },
    { name: "Bond Markets Unit European Monetary Unit (E.M.U.-6)", code: "XBB", },
    { name: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", code: "XBC", },
    { name: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", code: "XBD", },
    { name: "East Caribbean Dollar", code: "XCD", },
    { name: "SDR (Special Drawing Right)", code: "XDR", },
    { name: "CFA Franc BCEAO", code: "XOF", },
    { name: "Palladium", code: "XPD", },
    { name: "CFP Franc", code: "XPF", },
    { name: "Platinum", code: "XPT", },
    { name: "Sucre", code: "XSU", },
    { name: "Codes specifically reserved for testing purposes", code: "XTS", },
    { name: "ADB Unit of Account", code: "XUA", },
    { name: "The codes assigned for transactions where no currency is involved", code: "XXX", },
    { name: "Yemeni Rial", code: "YER", },
    { name: "Rand", code: "ZAR", },
    { name: "Zambian Kwacha", code: "ZMW", },
    { name: "Zimbabwe Dollar", code: "ZWL", },
];
