//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asm.BankPlus.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringTransaction
    {
        public int RecurringTransactionId { get; set; }
        public System.Guid SourceVirtualAccountId { get; set; }
        public System.Guid DestinationVirtualAccountId { get; set; }
        public string Description { get; set; }
        public Asm.BankPlus.Models.Schedule Schedule { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> LastRun { get; set; }
    
        public virtual VirtualAccount DestinationVirtualAccount { get; set; }
        public virtual VirtualAccount SourceVirtualAccount { get; set; }
    }
}
