//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asm.BankPlus.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public System.Guid VirtualAccountId { get; set; }
        public Asm.BankPlus.Models.TransactionType TransactionType { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.Guid> TransactionGroupId { get; set; }
        public string Description { get; set; }
        public System.DateTime TransactionTime { get; set; }
    
        public virtual VirtualAccount VirtualAccount { get; set; }
    }
}
