// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type Account = {
    utilityType: UtilityType;
    firstBill?: null | string;
    latestBill?: null | string;
    id: string;
    name: string;
    description?: null | string;
    balanceDate: string;
    currentBalance: number;
    currentBalanceLocalCurrency?: null | number;
    currency: string;
    controller: Controller;
    closedDate?: null | string;
    instrumentType?: null | string;
    groupId?: null | string;
    virtualInstruments: Array<VirtualInstrument>;
    remainingBalance?: null | number;
    remainingBalanceLocalCurrency?: null | number;
};

export type AccountScopeMode = 'AllAccounts' | 'SelectedAccounts';

export type AccountType = 'NotSet' | 'Transaction' | 'Savings' | 'Credit' | 'Mortgage' | 'Superannuation' | 'Investment' | 'Loan' | 'Broker';

export type AccountTypeSummary = {
    utilityType: UtilityType;
    from: string;
    accounts: Array<string>;
};

export type AllocationMode = 'EvenlySpread' | 'AllAtEnd';

export type AllTagAverageReport = {
    tags: Array<TagValue>;
    reportType: ReportType;
    accountId: string;
    start: string;
    end: string;
};

export type Asset = {
    purchasePrice?: null | number;
    shareWithFamily: boolean;
    id: string;
    name: string;
    description?: null | string;
    balanceDate: string;
    currentBalance: number;
    currentBalanceLocalCurrency?: null | number;
    currency: string;
    controller: Controller;
    closedDate?: null | string;
    instrumentType?: null | string;
    groupId?: null | string;
    virtualInstruments: Array<VirtualInstrument>;
    remainingBalance?: null | number;
    remainingBalanceLocalCurrency?: null | number;
};

export type Assumptions = {
    version: number;
    inflationRateAnnual?: null | number;
    applyInflationToBaseline: boolean;
    applyInflationToPlanned: boolean;
    safetyBuffer: number;
};

export type Bill = {
    id: number;
    accountId: string;
    accountName: string;
    invoiceNumber?: null | string;
    issueDate: string;
    currentReading?: null | number;
    previousReading?: null | number;
    total?: null | number;
    costsIncludeGST?: null | boolean;
    cost?: null | number;
    periods: Array<Period>;
    discounts: Array<Discount>;
};

export type BreakdownReport = {
    tags: Array<TagValue>;
    accountId: string;
    start: string;
    end: string;
};

export type Budget = {
    year: number;
    incomeLines: Array<BudgetLine>;
    expensesLines: Array<BudgetLine>;
    months: Array<BudgetMonth>;
};

export type BudgetLine = {
    id: string;
    name: string;
    tagId: number;
    notes?: null | string;
    amount: number;
    month: number;
    type: BudgetLineType;
};

export type BudgetLineType = 'Income' | 'Expenses';

export type BudgetMonth = {
    month: number;
    income: number;
    expenses: number;
    remainder: number;
};

export type BudgetReportByMonth = {
    items: Array<BudgetReportValueMonth>;
};

export type BudgetReportByMonthBreakdown = {
    tags: Array<BudgetReportValueTag>;
};

export type BudgetReportValueMonth = {
    month: number;
    budgetedAmount: number;
    actual: null | number;
};

export type BudgetReportValueTag = {
    name: string;
    budgetedAmount: number;
    actual: null | number;
};

export type ByTagReport = {
    tags: Array<TagValue>;
    accountId: string;
    start: string;
    end: string;
};

export type Controller = 'Manual' | 'Virtual' | 'Import';

export type CostDataPoint = {
    date: string;
    accountName: string;
    averagePricePerUnit: number;
    totalUsage: number;
};

export type CostPerUnitReport = {
    start: string;
    end: string;
    dataPoints: Array<CostDataPoint>;
};

export type CreateAccount = {
    name: string;
    description?: null | string;
    importerTypeId?: null | number;
    institutionId: number;
    currency: string;
    balance: number;
    openedDate?: null | string;
    groupId?: null | string;
    accountType: AccountType;
    controller: Controller;
    includeInBudget: boolean;
    shareWithFamily: boolean;
};

export type CreateAsset = {
    name: string;
    description: string;
    purchasePrice?: null | number;
    currentBalance: number;
    shareWithFamily: boolean;
    groupId?: null | string;
};

export type CreateBill = {
    invoiceNumber?: null | string;
    issueDate: string;
    currentReading?: null | number;
    previousReading?: null | number;
    total?: null | number;
    costsIncludeGST?: null | boolean;
    cost?: null | number;
    periods: Array<Period>;
    discounts: Array<Discount>;
};

export type CreateBillAccount = {
    name: string;
    description?: null | string;
    utilityType: UtilityType;
    accountNumber: string;
    institutionId?: null | number;
    currency: string;
    shareWithFamily: boolean;
};

export type CreateByName = {
    name: string;
    tags: Array<number>;
};

export type CreateFamily = {
    name: string;
};

export type CreateGroup = {
    name: string;
    description: string;
    showTotal: boolean;
};

export type CreateInstitution = {
    name: string;
    institutionType: InstitutionType;
};

export type CreateInstitutionAccount = {
    institutionId: number;
    importerTypeId?: null | number;
    name: string;
    openedDate: string;
};

export type CreateRecurringTransaction = {
    accountId: string;
    virtualAccountId: string;
    description: null | string;
    amount: number;
    schedule: ScheduleFrequency;
    nextRun: string;
    instrumentId: string;
};

export type CreateRule = {
    instrumentId: string;
    contains: string;
    description: null | string;
    tags: Array<Tag>;
};

export type CreateStock = {
    name: string;
    description: string;
    symbol: string;
    price: number;
    quantity: number;
    fees: number;
    shareWithFamily: boolean;
    groupId?: null | string;
};

export type CreateStockTransaction = {
    quantity: number;
    price: number;
    fees: number;
    description: string;
    date: string;
    instrumentId: string;
};

export type CreateTag = {
    tag: Tag;
};

export type CreateTransaction = {
    amount: number;
    description: string;
    reference: null | string;
    transactionTime: string;
};

export type CreateVirtualInstrument = {
    name: string;
    description?: null | string;
    openingBalance: number;
    controller: Controller;
};

export type Discount = {
    discountPercent?: null | number;
    discountAmount?: null | number;
    reason?: null | string;
};

export type Family = {
    id: string;
    name: string;
    members: Array<User>;
};

export type ForecastMonth = {
    monthStart: string;
    openingBalance: number;
    incomeTotal: number;
    baselineOutgoingsTotal: number;
    plannedItemsTotal: number;
    closingBalance: number;
    actualBalance?: null | number;
};

export type ForecastPlan = {
    id: string;
    isArchived: boolean;
    createdUtc: string;
    updatedUtc: string;
    name: string;
    startDate: string;
    endDate: string;
    accountScopeMode: AccountScopeMode;
    startingBalanceMode: StartingBalanceMode;
    startingBalanceAmount?: null | number;
    currencyCode?: null | string;
    incomeStrategy?: null | IncomeStrategy;
    outgoingStrategy?: null | OutgoingStrategy;
    assumptions?: null | Assumptions;
    accountIds: Array<string>;
    plannedItems: Array<PlannedItem>;
};

export type ForecastResult = {
    planId: string;
    months: Array<ForecastMonth>;
    summary: ForecastSummary;
};

export type ForecastSummary = {
    lowestBalance: number;
    lowestBalanceMonth: string;
    requiredMonthlyUplift: number;
    monthsBelowZero: number;
    totalIncome: number;
    totalOutgoings: number;
    monthlyBaselineOutgoings: number;
    regression?: null | RegressionDiagnostics;
};

export type Group = {
    id: string;
    name: string;
    description?: null | string;
    showTotal: boolean;
};

export type HexColour = unknown;

export type HistoricalIncomeSettings = {
    lookbackMonths: number;
    includeTagIds?: null | Array<number>;
    excludeTagIds?: null | Array<number>;
    excludeTransfers: boolean;
    excludeOffsets: boolean;
};

export type IFormFile = Blob | File;

export type Import = {
    bills: Array<ImportBill>;
};

export type ImportBill = {
    accountName: string;
    invoiceNumber?: null | string;
    issueDate: string;
    currentReading?: null | number;
    previousReading?: null | number;
    total?: null | number;
    costsIncludeGST?: null | boolean;
    cost?: null | number;
    periods: Array<Period>;
    discounts: Array<Discount>;
};

export type ImporterType = {
    id: number;
    type: string;
    name: string;
};

export type ImportResult = {
    imported: number;
    failed: number;
    errors: Array<string>;
};

export type IncomeCorrelatedSettings = {
    rSquaredThreshold: number;
    minDataPoints: number;
};

export type IncomeStrategy = {
    version: number;
    mode: string;
    manualRecurring?: null | ManualRecurringIncome;
    manualAdjustments?: null | Array<ManualAdjustment>;
    historical?: null | HistoricalIncomeSettings;
};

export type InOutReport = {
    income: number;
    outgoings: number;
    accountId: string;
    start: string;
    end: string;
};

export type InOutTrendReport = {
    income: Array<TrendPoint>;
    expenses: Array<TrendPoint>;
    accountId: string;
    start: string;
    end: string;
};

export type Institution = {
    id: number;
    name: string;
    institutionType: InstitutionType;
};

export type InstitutionAccount = {
    id: string;
    importerTypeId?: null | number;
    institutionId: number;
    name: string;
    openedDate: string;
    closedDate?: null | string;
};

export type InstitutionType = 'Bank' | 'SuperannuationFund' | 'Broker' | 'CreditUnion' | 'BuildingSociety' | 'InvestmentFund' | 'Government' | 'Other' | 'Utility';

export type Instrument = {
    id: string;
    name: string;
    description?: null | string;
    balanceDate: string;
    currentBalance: number;
    currentBalanceLocalCurrency?: null | number;
    currency: string;
    controller: Controller;
    closedDate?: null | string;
    instrumentType?: null | string;
    groupId?: null | string;
    virtualInstruments: Array<VirtualInstrument>;
    remainingBalance?: null | number;
    remainingBalanceLocalCurrency?: null | number;
};

export type InstrumentGroup = {
    id?: null | string;
    name: string;
    instruments: Array<Instrument>;
    showTotal: boolean;
    total?: null | number;
};

export type InstrumentsList = {
    groups: Array<InstrumentGroup>;
    total: number;
};

export type ListItem = {
    id: string;
    name: string;
};

export type LogicalAccount = {
    accountType: AccountType;
    isPrimary: boolean;
    shareWithFamily: boolean;
    includeInBudget: boolean;
    institutionAccounts: Array<InstitutionAccount>;
    lastTransaction?: null | string;
    id: string;
    name: string;
    description?: null | string;
    balanceDate: string;
    currentBalance: number;
    currentBalanceLocalCurrency?: null | number;
    currency: string;
    controller: Controller;
    closedDate?: null | string;
    instrumentType?: null | string;
    groupId?: null | string;
    virtualInstruments: Array<VirtualInstrument>;
    remainingBalance?: null | number;
    remainingBalanceLocalCurrency?: null | number;
};

export type ManualAdjustment = {
    date: string;
    deltaAmount: number;
};

export type ManualRecurringIncome = {
    amount: number;
    frequency: string;
    startDate?: null | string;
    endDate?: null | string;
};

export type MonthlyBalancesReport = {
    balances: Array<TrendPoint>;
    accountId: string;
    start: string;
    end: string;
};

export type OutgoingStrategy = {
    version: number;
    mode: string;
    lookbackMonths: number;
    excludeTagIds?: null | Array<number>;
    excludeAboveAmount?: null | number;
    seasonality?: null | SeasonalitySettings;
    incomeCorrelated?: null | IncomeCorrelatedSettings;
};

export type Period = {
    periodStart: string;
    periodEnd: string;
    daysInclusive?: null | number;
    days?: null | number;
    pricePerUnit: number;
    totalUsage: number;
    cost?: null | number;
    chargePerDay: number;
};

export type PlannedItem = {
    id: string;
    itemType: PlannedItemType;
    name: string;
    amount: number;
    tagId?: null | number;
    tagName?: null | string;
    virtualInstrumentId?: null | string;
    isIncluded: boolean;
    dateMode: PlannedItemDateMode;
    fixedDate?: null | string;
    scheduleFrequency?: null | ScheduleFrequency;
    scheduleAnchorDate?: null | string;
    scheduleInterval?: null | number;
    scheduleDayOfMonth?: null | number;
    scheduleEndDate?: null | string;
    windowStartDate?: null | string;
    windowEndDate?: null | string;
    allocationMode?: null | AllocationMode;
    notes?: null | string;
};

export type PlannedItemDateMode = 'FixedDate' | 'Schedule' | 'FlexibleWindow';

export type PlannedItemType = 'Expense' | 'Income';

export type RecurringTransaction = {
    id: string;
    virtualAccountId: string;
    description?: null | string;
    amount: number;
    lastRun?: null | string;
    nextRun: string;
    schedule: ScheduleFrequency;
};

export type RegressionDiagnostics = {
    fixedComponent: number;
    variableComponent: number;
    rSquared: number;
    fellBackToFlatAverage: boolean;
};

export type ReportInterval = 'Monthly' | 'Yearly';

export type ReportType = {
    [key: string]: unknown;
};

export type Rule = {
    id: number;
    contains: string;
    description?: null | string;
    tags: Array<Tag>;
};

export type ScheduleFrequency = 'Daily' | 'Weekly' | 'Monthly' | 'Yearly' | 'Fortnightly';

export type SeasonalitySettings = {
    enabled: boolean;
};

export type ServiceChargeDataPoint = {
    date: string;
    accountName: string;
    averageChargePerDay: number;
};

export type ServiceChargeReport = {
    start: string;
    end: string;
    dataPoints: Array<ServiceChargeDataPoint>;
};

export type SimpleBudgetLine = {
    tagId: number;
    notes?: null | string;
    amount: number;
    month: number;
    type: BudgetLineType;
};

export type SimpleForecastPlan = {
    name: string;
    startDate: string;
    endDate: string;
    accountScopeMode: AccountScopeMode;
    startingBalanceMode: StartingBalanceMode;
    startingBalanceAmount?: null | number;
    currencyCode?: null | string;
    incomeStrategy?: null | IncomeStrategy;
    outgoingStrategy?: null | OutgoingStrategy;
    assumptions?: null | Assumptions;
    accountIds: Array<string>;
    plannedItems: Array<PlannedItem>;
};

export type SimplePlannedItem = {
    itemType: PlannedItemType;
    name: string;
    amount: number;
    tagId?: null | number;
    tagName?: null | string;
    virtualInstrumentId?: null | string;
    isIncluded: boolean;
    dateMode: PlannedItemDateMode;
    fixedDate?: null | string;
    scheduleFrequency?: null | ScheduleFrequency;
    scheduleAnchorDate?: null | string;
    scheduleInterval?: null | number;
    scheduleDayOfMonth?: null | number;
    scheduleEndDate?: null | string;
    windowStartDate?: null | string;
    windowEndDate?: null | string;
    allocationMode?: null | AllocationMode;
    notes?: null | string;
};

export type SimpleTag = {
    id: number;
    name: string;
};

export type SortDirection = 'Ascending' | 'Descending';

export type StartingBalanceMode = 'CalculatedCurrent' | 'ManualAmount';

export type StockHolding = {
    symbol: string;
    quantity: number;
    currentPrice: number;
    currentValue: number;
    gainLoss: number;
    shareWithFamily: boolean;
    id: string;
    name: string;
    description?: null | string;
    balanceDate: string;
    currentBalance: number;
    currentBalanceLocalCurrency?: null | number;
    currency: string;
    controller: Controller;
    closedDate?: null | string;
    instrumentType?: null | string;
    groupId?: null | string;
    virtualInstruments: Array<VirtualInstrument>;
    remainingBalance?: null | number;
    remainingBalanceLocalCurrency?: null | number;
};

export type StockHoldingReport = {
    accountId: string;
    currentValue: number;
    profitLoss: number;
    adjustedProfitLoss: number;
};

export type StockTransaction = {
    id: string;
    accountId: string;
    price: number;
    quantity: number;
    description?: null | string;
    fees: number;
    accountHolderName?: null | string;
    transactionDate: string;
    transactionType: TransactionType;
};

export type StockValueReport = {
    instrumentId: string;
    symbol: string;
    start: string;
    end: string;
    granularity: number;
    points: Array<StockValueReportPoint>;
    investment: Array<StockValueReportPoint>;
};

export type StockValueReportPoint = {
    date: string;
    value: number;
};

export type Tag = {
    colour?: null | HexColour;
    tags: Array<Tag>;
    settings: TagSettings;
    id: number;
    name: string;
};

export type TagHierarchy = {
    levels: {
        [key: string]: number;
    };
    tags: Array<Tag>;
};

export type TagSettings = {
    applySmoothing: boolean;
    excludeFromReporting: boolean;
};

export type TagTrendReport = {
    tagId: number;
    tagName: string;
    months: Array<TrendPoint>;
    average: number;
    offsetAverage?: null | number;
    accountId: string;
    start: string;
    end: string;
};

export type TagValue = {
    tagId?: null | number;
    tagName?: null | string;
    grossAmount: number;
    netAmount?: null | number;
    hasChildren: boolean;
};

export type Transaction = {
    id: string;
    accountId: string;
    amount: number;
    netAmount: number;
    description?: null | string;
    location?: null | string;
    accountHolderName?: null | string;
    reference?: null | string;
    notes?: null | string;
    excludeFromReporting: boolean;
    transactionTime: string;
    purchaseDate?: null | string;
    transactionType: TransactionType;
    tags: Array<SimpleTag>;
    splits: Array<TransactionSplit>;
    offsetFor: Array<TransactionOffsetFor>;
    extraInfo?: unknown;
};

export type TransactionFilterType = 'None' | 'Credit' | 'Debit';

export type TransactionOffsetBy = {
    transaction: Transaction;
    amount: number;
};

export type TransactionOffsetFor = {
    transaction: Transaction;
    amount: number;
};

export type TransactionSplit = {
    id: string;
    tags: Array<SimpleTag>;
    amount: number;
    offsetBy: Array<TransactionOffsetBy>;
};

export type TransactionType = 'NotSet' | 'Credit' | 'Debit';

export type TrendPoint = {
    month: string;
    grossAmount: number;
    netAmount?: null | number;
};

export type UpdateAsset = {
    accountId: string;
    name: string;
    description: string;
    shareWithFamily: boolean;
    purchasePrice?: null | number;
    currentBalance: number;
    groupId?: null | string;
};

export type UpdateBalance = {
    instrumentId: string;
    virtualInstrumentId: string;
    balance: number;
};

export type UpdateFamily = {
    name: string;
};

export type UpdateInstitution = {
    id: number;
    name: string;
    institutionType: InstitutionType;
};

export type UpdateInstitutionAccount = {
    institutionId: number;
    importerTypeId?: null | number;
    name: string;
};

export type UpdateRecurringTransaction = {
    accountId: string;
    virtualAccountId: string;
    recurringTransactionId: string;
    description: null | string;
    amount: number;
    schedule: ScheduleFrequency;
    nextRun: string;
    instrumentId: string;
};

export type UpdateRule = {
    contains: string;
    description?: null | string;
    tags: Array<Tag>;
};

export type UpdateStock = {
    instrumentId: string;
    name: string;
    description: string;
    shareWithFamily: boolean;
    currentPrice: number;
    groupId?: null | string;
};

export type UpdateTag = {
    name: string;
    colour: null | HexColour;
    excludeFromReporting: boolean;
    applySmoothing: boolean;
};

export type UpdateTransaction = {
    instrumentId: string;
    id: string;
    notes: null | string;
    splits: Array<TransactionSplit>;
    excludeFromReporting: boolean;
};

export type UpdateUser = {
    primaryAccountId?: null | string;
    currency: string;
    cards: Array<UserCard>;
};

export type UpdateVirtualInstrument = {
    instrumentId: string;
    virtualInstrumentId: string;
    name: string;
    description: string;
    currentBalance: number;
};

export type UsageDataPoint = {
    date: string;
    accountName: string;
    usagePerDay: number;
};

export type UsageReport = {
    start: string;
    end: string;
    dataPoints: Array<UsageDataPoint>;
};

export type User = {
    id: string;
    emailAddress: string;
    firstName?: null | string;
    lastName?: null | string;
    currency: string;
    familyId: string;
    primaryAccountId?: null | string;
    accounts: Array<string>;
    sharedAccounts: Array<string>;
    groups: Array<string>;
};

export type UserCard = {
    name?: null | string;
    last4Digits: number;
};

export type UserWithCards = {
    cards: Array<UserCard>;
    id: string;
    emailAddress: string;
    firstName?: null | string;
    lastName?: null | string;
    currency: string;
    familyId: string;
    primaryAccountId?: null | string;
    accounts: Array<string>;
    sharedAccounts: Array<string>;
    groups: Array<string>;
};

export type UtilityType = 'Electricity' | 'Gas' | 'Water' | 'Phone' | 'Internet' | 'Other';

export type VirtualInstrument = {
    parentId: string;
    lastTransaction?: null | string;
    id: string;
    name: string;
    description?: null | string;
    balanceDate: string;
    currentBalance: number;
    currentBalanceLocalCurrency?: null | number;
    currency: string;
    controller: Controller;
    closedDate?: null | string;
    instrumentType?: null | string;
    groupId?: null | string;
    virtualInstruments: Array<VirtualInstrument>;
    remainingBalance?: null | number;
    remainingBalanceLocalCurrency?: null | number;
};

export type GetAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts';
};

export type GetAccountsResponses = {
    /**
     * OK
     */
    200: Array<LogicalAccount>;
};

export type GetAccountsResponse = GetAccountsResponses[keyof GetAccountsResponses];

export type CreateAccountData = {
    body: CreateAccount;
    path?: never;
    query?: never;
    url: '/api/accounts';
};

export type CreateAccountResponses = {
    /**
     * Created
     */
    201: LogicalAccount;
};

export type CreateAccountResponse = CreateAccountResponses[keyof CreateAccountResponses];

export type GetAccountData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}';
};

export type GetAccountResponses = {
    /**
     * OK
     */
    200: LogicalAccount;
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type UpdateAccountData = {
    body: LogicalAccount;
    path?: never;
    query?: never;
    url: '/api/accounts/{id}';
};

export type UpdateAccountResponses = {
    /**
     * OK
     */
    200: LogicalAccount;
};

export type UpdateAccountResponse = UpdateAccountResponses[keyof UpdateAccountResponses];

export type GetInstitutionAccountData = {
    body?: never;
    path: {
        instrumentId: string;
        id: string;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}/institution-accounts/{id}';
};

export type GetInstitutionAccountResponses = {
    /**
     * OK
     */
    200: InstitutionAccount;
};

export type GetInstitutionAccountResponse = GetInstitutionAccountResponses[keyof GetInstitutionAccountResponses];

export type UpdateInstitutionAccountData = {
    body: UpdateInstitutionAccount;
    path: {
        instrumentId: string;
        id: string;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}/institution-accounts/{id}';
};

export type UpdateInstitutionAccountResponses = {
    /**
     * OK
     */
    200: InstitutionAccount;
};

export type UpdateInstitutionAccountResponse = UpdateInstitutionAccountResponses[keyof UpdateInstitutionAccountResponses];

export type CreateInstitutionAccountData = {
    body: CreateInstitutionAccount;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}/institution-accounts';
};

export type CreateInstitutionAccountResponses = {
    /**
     * Created
     */
    201: InstitutionAccount;
};

export type CreateInstitutionAccountResponse = CreateInstitutionAccountResponses[keyof CreateInstitutionAccountResponses];

export type CloseInstitutionAccountData = {
    body?: never;
    path: {
        instrumentId: string;
        id: string;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}/institution-accounts/{id}/close';
};

export type CloseInstitutionAccountResponses = {
    /**
     * OK
     */
    200: InstitutionAccount;
};

export type CloseInstitutionAccountResponse = CloseInstitutionAccountResponses[keyof CloseInstitutionAccountResponses];

export type GetAllRecurringTransactionsData = {
    body?: never;
    path: {
        accountId: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/recurring';
};

export type GetAllRecurringTransactionsResponses = {
    /**
     * OK
     */
    200: Array<RecurringTransaction>;
};

export type GetAllRecurringTransactionsResponse = GetAllRecurringTransactionsResponses[keyof GetAllRecurringTransactionsResponses];

export type CreateRecurringTransactionData = {
    body: CreateRecurringTransaction;
    path?: never;
    query?: never;
    url: '/api/accounts/{accountId}/recurring';
};

export type CreateRecurringTransactionResponses = {
    /**
     * OK
     */
    200: RecurringTransaction;
    /**
     * Created
     */
    201: RecurringTransaction;
};

export type CreateRecurringTransactionResponse = CreateRecurringTransactionResponses[keyof CreateRecurringTransactionResponses];

export type DeleteRecurringTransactionData = {
    body?: never;
    path: {
        accountId: string;
        recurringTransactionId: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/recurring/{recurringTransactionId}';
};

export type DeleteRecurringTransactionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRecurringTransactionResponse = DeleteRecurringTransactionResponses[keyof DeleteRecurringTransactionResponses];

export type GetRecurringTransactionData = {
    body?: never;
    path: {
        accountId: string;
        recurringTransactionId: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/recurring/{recurringTransactionId}';
};

export type GetRecurringTransactionResponses = {
    /**
     * OK
     */
    200: RecurringTransaction;
};

export type GetRecurringTransactionResponse = GetRecurringTransactionResponses[keyof GetRecurringTransactionResponses];

export type UpdateRecurringTransactionData = {
    body: UpdateRecurringTransaction;
    path?: never;
    query?: never;
    url: '/api/accounts/{accountId}/recurring/{recurringTransactionId}';
};

export type UpdateRecurringTransactionResponses = {
    /**
     * OK
     */
    200: RecurringTransaction;
};

export type UpdateRecurringTransactionResponse = UpdateRecurringTransactionResponses[keyof UpdateRecurringTransactionResponses];

export type GetRecurringTransactionsForAVirtualAccountData = {
    body?: never;
    path: {
        accountId: string;
        virtualAccountId: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/virtual/{virtualAccountId}/recurring';
};

export type GetRecurringTransactionsForAVirtualAccountResponses = {
    /**
     * OK
     */
    200: Array<RecurringTransaction>;
};

export type GetRecurringTransactionsForAVirtualAccountResponse = GetRecurringTransactionsForAVirtualAccountResponses[keyof GetRecurringTransactionsForAVirtualAccountResponses];

export type GetAssetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/assets/{id}';
};

export type GetAssetResponses = {
    /**
     * OK
     */
    200: Asset;
};

export type GetAssetResponse = GetAssetResponses[keyof GetAssetResponses];

export type UpdateAssetData = {
    body: UpdateAsset;
    path?: never;
    query?: never;
    url: '/api/assets/{id}';
};

export type UpdateAssetResponses = {
    /**
     * OK
     */
    200: Asset;
};

export type UpdateAssetResponse = UpdateAssetResponses[keyof UpdateAssetResponses];

export type CreateAssetData = {
    body: CreateAsset;
    path?: never;
    query?: never;
    url: '/api/assets';
};

export type CreateAssetResponses = {
    /**
     * Created
     */
    201: Asset;
};

export type CreateAssetResponse = CreateAssetResponses[keyof CreateAssetResponses];

export type GetAllBillsData = {
    body?: never;
    path?: never;
    query: {
        PageSize: number;
        PageNumber: number;
        StartDate?: string;
        EndDate?: string;
        AccountId?: string;
        UtilityType?: UtilityType;
    };
    url: '/api/bills';
};

export type GetAllBillsResponses = {
    /**
     * OK
     */
    200: Array<Bill>;
};

export type GetAllBillsResponse = GetAllBillsResponses[keyof GetAllBillsResponses];

export type GetBillAccountSummariesByTypeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bills/accounts/types';
};

export type GetBillAccountSummariesByTypeResponses = {
    /**
     * OK
     */
    200: Array<AccountTypeSummary>;
};

export type GetBillAccountSummariesByTypeResponse = GetBillAccountSummariesByTypeResponses[keyof GetBillAccountSummariesByTypeResponses];

export type GetBillAccountsByTypeData = {
    body?: never;
    path: {
        type: UtilityType;
    };
    query?: never;
    url: '/api/bills/accounts/types/{type}';
};

export type GetBillAccountsByTypeResponses = {
    /**
     * OK
     */
    200: Array<Account>;
};

export type GetBillAccountsByTypeResponse = GetBillAccountsByTypeResponses[keyof GetBillAccountsByTypeResponses];

export type GetBillAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bills/accounts';
};

export type GetBillAccountsResponses = {
    /**
     * OK
     */
    200: Array<Account>;
};

export type GetBillAccountsResponse = GetBillAccountsResponses[keyof GetBillAccountsResponses];

export type CreateBillAccountData = {
    body: CreateBillAccount;
    path?: never;
    query?: never;
    url: '/api/bills/accounts';
};

export type CreateBillAccountResponses = {
    /**
     * Created
     */
    201: Account;
};

export type CreateBillAccountResponse = CreateBillAccountResponses[keyof CreateBillAccountResponses];

export type GetBillsByUtilityTypeData = {
    body?: never;
    path: {
        utilityType: UtilityType;
    };
    query: {
        PageSize: number;
        PageNumber: number;
        StartDate?: string;
        EndDate?: string;
        AccountId?: string;
    };
    url: '/api/bills/types/{utilityType}/bills';
};

export type GetBillsByUtilityTypeResponses = {
    /**
     * OK
     */
    200: Array<Bill>;
};

export type GetBillsByUtilityTypeResponse = GetBillsByUtilityTypeResponses[keyof GetBillsByUtilityTypeResponses];

export type ImportBillsData = {
    body: Import;
    path?: never;
    query?: never;
    url: '/api/bills/import';
};

export type ImportBillsResponses = {
    /**
     * OK
     */
    200: ImportResult;
};

export type ImportBillsResponse = ImportBillsResponses[keyof ImportBillsResponses];

export type GetBillAccountData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/bills/accounts/{instrumentId}';
};

export type GetBillAccountResponses = {
    /**
     * OK
     */
    200: Account;
};

export type GetBillAccountResponse = GetBillAccountResponses[keyof GetBillAccountResponses];

export type GetBillsForAnAccountData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: {
        PageSize?: number;
        PageNumber?: number;
    };
    url: '/api/bills/accounts/{instrumentId}/bills';
};

export type GetBillsForAnAccountResponses = {
    /**
     * OK
     */
    200: Array<Bill>;
};

export type GetBillsForAnAccountResponse = GetBillsForAnAccountResponses[keyof GetBillsForAnAccountResponses];

export type CreateBillData = {
    body: CreateBill;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/bills/accounts/{instrumentId}/bills';
};

export type CreateBillResponses = {
    /**
     * Created
     */
    201: Bill;
};

export type CreateBillResponse = CreateBillResponses[keyof CreateBillResponses];

export type GetBillData = {
    body?: never;
    path: {
        instrumentId: string;
        id: number;
    };
    query?: never;
    url: '/api/bills/accounts/{instrumentId}/bills/{id}';
};

export type GetBillResponses = {
    /**
     * OK
     */
    200: Bill;
};

export type GetBillResponse = GetBillResponses[keyof GetBillResponses];

export type GetCostPerUnitReportData = {
    body?: never;
    path?: never;
    query: {
        Start: string;
        End: string;
        AccountId?: string;
        UtilityType?: UtilityType;
    };
    url: '/api/bills/reports/cost-per-unit';
};

export type GetCostPerUnitReportResponses = {
    /**
     * OK
     */
    200: CostPerUnitReport;
};

export type GetCostPerUnitReportResponse = GetCostPerUnitReportResponses[keyof GetCostPerUnitReportResponses];

export type GetServiceChargeReportData = {
    body?: never;
    path?: never;
    query: {
        Start: string;
        End: string;
        AccountId?: string;
        UtilityType?: UtilityType;
    };
    url: '/api/bills/reports/service-charge';
};

export type GetServiceChargeReportResponses = {
    /**
     * OK
     */
    200: ServiceChargeReport;
};

export type GetServiceChargeReportResponse = GetServiceChargeReportResponses[keyof GetServiceChargeReportResponses];

export type GetUsageReportData = {
    body?: never;
    path?: never;
    query: {
        Start: string;
        End: string;
        AccountId?: string;
        UtilityType?: UtilityType;
    };
    url: '/api/bills/reports/usage';
};

export type GetUsageReportResponses = {
    /**
     * OK
     */
    200: UsageReport;
};

export type GetUsageReportResponse = GetUsageReportResponses[keyof GetUsageReportResponses];

export type GetAllBudgetYearsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/budget';
};

export type GetAllBudgetYearsResponses = {
    /**
     * OK
     */
    200: Array<number>;
};

export type GetAllBudgetYearsResponse = GetAllBudgetYearsResponses[keyof GetAllBudgetYearsResponses];

export type GetBudgetData = {
    body?: never;
    path: {
        year: number;
    };
    query?: never;
    url: '/api/budget/{year}';
};

export type GetBudgetResponses = {
    /**
     * OK
     */
    200: Budget;
};

export type GetBudgetResponse = GetBudgetResponses[keyof GetBudgetResponses];

export type DeleteBudgetLineData = {
    body?: never;
    path: {
        year: number;
        id: string;
    };
    query?: never;
    url: '/api/budget/{year}/lines/{id}';
};

export type DeleteBudgetLineResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteBudgetLineResponse = DeleteBudgetLineResponses[keyof DeleteBudgetLineResponses];

export type GetBudgetLineData = {
    body?: never;
    path: {
        year: number;
        id: string;
    };
    query?: never;
    url: '/api/budget/{year}/lines/{id}';
};

export type GetBudgetLineResponses = {
    /**
     * OK
     */
    200: BudgetLine;
};

export type GetBudgetLineResponse = GetBudgetLineResponses[keyof GetBudgetLineResponses];

export type UpdateBudgetLineData = {
    body: SimpleBudgetLine;
    path: {
        year: number;
        id: string;
    };
    query?: never;
    url: '/api/budget/{year}/lines/{id}';
};

export type UpdateBudgetLineResponses = {
    /**
     * OK
     */
    200: BudgetLine;
};

export type UpdateBudgetLineResponse = UpdateBudgetLineResponses[keyof UpdateBudgetLineResponses];

export type CreateBudgetLineData = {
    body: SimpleBudgetLine;
    path: {
        year: number;
    };
    query?: never;
    url: '/api/budget/{year}/lines';
};

export type CreateBudgetLineResponses = {
    /**
     * OK
     */
    200: BudgetLine;
    /**
     * Created
     */
    201: BudgetLine;
};

export type CreateBudgetLineResponse = CreateBudgetLineResponses[keyof CreateBudgetLineResponses];

export type GetBudgetAmountForTagData = {
    body?: never;
    path: {
        tagId: number;
    };
    query?: never;
    url: '/api/budget/tag/{tagId}';
};

export type GetBudgetAmountForTagResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetBudgetAmountForTagResponse = GetBudgetAmountForTagResponses[keyof GetBudgetAmountForTagResponses];

export type GetBudgetReportData = {
    body?: never;
    path: {
        year: number;
    };
    query?: never;
    url: '/api/budget/{year}/report';
};

export type GetBudgetReportResponses = {
    /**
     * OK
     */
    200: BudgetReportByMonth;
};

export type GetBudgetReportResponse = GetBudgetReportResponses[keyof GetBudgetReportResponses];

export type GetBudgetReportForMonthData = {
    body?: never;
    path: {
        year: number;
        month: number;
    };
    query?: never;
    url: '/api/budget/{year}/report/{month}';
};

export type GetBudgetReportForMonthResponses = {
    /**
     * OK
     */
    200: BudgetReportValueMonth;
};

export type GetBudgetReportForMonthResponse = GetBudgetReportForMonthResponses[keyof GetBudgetReportForMonthResponses];

export type GetBudgetReportBreakdownForMonthData = {
    body?: never;
    path: {
        year: number;
        month: number;
    };
    query?: never;
    url: '/api/budget/{year}/report/{month}/breakdown';
};

export type GetBudgetReportBreakdownForMonthResponses = {
    /**
     * OK
     */
    200: BudgetReportByMonthBreakdown;
};

export type GetBudgetReportBreakdownForMonthResponse = GetBudgetReportBreakdownForMonthResponses[keyof GetBudgetReportBreakdownForMonthResponses];

export type GetBudgetReportBreakdownForMonthForUnbudgetedItemsData = {
    body?: never;
    path: {
        year: number;
        month: number;
    };
    query?: never;
    url: '/api/budget/{year}/report/{month}/breakdown/unbudgeted';
};

export type GetBudgetReportBreakdownForMonthForUnbudgetedItemsResponses = {
    /**
     * OK
     */
    200: BudgetReportByMonthBreakdown;
};

export type GetBudgetReportBreakdownForMonthForUnbudgetedItemsResponse = GetBudgetReportBreakdownForMonthForUnbudgetedItemsResponses[keyof GetBudgetReportBreakdownForMonthForUnbudgetedItemsResponses];

export type GetMyFamilyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/families';
};

export type GetMyFamilyResponses = {
    /**
     * OK
     */
    200: Family;
};

export type GetMyFamilyResponse = GetMyFamilyResponses[keyof GetMyFamilyResponses];

export type UpdateMyFamilyData = {
    body: UpdateFamily;
    path?: never;
    query?: never;
    url: '/api/families';
};

export type UpdateMyFamilyResponses = {
    /**
     * OK
     */
    200: Family;
};

export type UpdateMyFamilyResponse = UpdateMyFamilyResponses[keyof UpdateMyFamilyResponses];

export type RemoveFamilyMemberData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/families/members/{userId}';
};

export type RemoveFamilyMemberResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveFamilyMemberResponse = RemoveFamilyMemberResponses[keyof RemoveFamilyMemberResponses];

export type GetAllFamiliesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/families/admin';
};

export type GetAllFamiliesResponses = {
    /**
     * OK
     */
    200: Array<Family>;
};

export type GetAllFamiliesResponse = GetAllFamiliesResponses[keyof GetAllFamiliesResponses];

export type CreateFamilyData = {
    body: CreateFamily;
    path?: never;
    query?: never;
    url: '/api/families/admin';
};

export type CreateFamilyResponses = {
    /**
     * Created
     */
    201: Family;
};

export type CreateFamilyResponse = CreateFamilyResponses[keyof CreateFamilyResponses];

export type GetFamilyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/families/admin/{id}';
};

export type GetFamilyResponses = {
    /**
     * OK
     */
    200: Family;
};

export type GetFamilyResponse = GetFamilyResponses[keyof GetFamilyResponses];

export type UpdateFamilyData = {
    body: UpdateFamily;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/families/admin/{id}';
};

export type UpdateFamilyResponses = {
    /**
     * OK
     */
    200: Family;
};

export type UpdateFamilyResponse = UpdateFamilyResponses[keyof UpdateFamilyResponses];

export type GetAllForecastPlansData = {
    body?: never;
    path?: never;
    query?: {
        IncludeArchived?: boolean;
    };
    url: '/api/forecast/plans';
};

export type GetAllForecastPlansResponses = {
    /**
     * OK
     */
    200: Array<ForecastPlan>;
};

export type GetAllForecastPlansResponse = GetAllForecastPlansResponses[keyof GetAllForecastPlansResponses];

export type CreateForecastPlanData = {
    body: ForecastPlan;
    path?: never;
    query?: never;
    url: '/api/forecast/plans';
};

export type CreateForecastPlanResponses = {
    /**
     * Created
     */
    201: ForecastPlan;
};

export type CreateForecastPlanResponse = CreateForecastPlanResponses[keyof CreateForecastPlanResponses];

export type DeleteForecastPlanData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/forecast/plans/{id}';
};

export type DeleteForecastPlanResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteForecastPlanResponse = DeleteForecastPlanResponses[keyof DeleteForecastPlanResponses];

export type GetForecastPlanData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/forecast/plans/{id}';
};

export type GetForecastPlanResponses = {
    /**
     * OK
     */
    200: ForecastPlan;
};

export type GetForecastPlanResponse = GetForecastPlanResponses[keyof GetForecastPlanResponses];

export type UpdateForecastPlanData = {
    body: SimpleForecastPlan;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/forecast/plans/{id}';
};

export type UpdateForecastPlanResponses = {
    /**
     * OK
     */
    200: ForecastPlan;
};

export type UpdateForecastPlanResponse = UpdateForecastPlanResponses[keyof UpdateForecastPlanResponses];

export type ArchiveForecastPlanData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/forecast/plans/{id}/archive';
};

export type ArchiveForecastPlanResponses = {
    /**
     * OK
     */
    200: ForecastPlan;
};

export type ArchiveForecastPlanResponse = ArchiveForecastPlanResponses[keyof ArchiveForecastPlanResponses];

export type RunForecastData = {
    body?: never;
    path: {
        planId: string;
    };
    query?: never;
    url: '/api/forecast/plans/{planId}/run';
};

export type RunForecastResponses = {
    /**
     * OK
     */
    200: ForecastResult;
};

export type RunForecastResponse = RunForecastResponses[keyof RunForecastResponses];

export type DeletePlannedItemData = {
    body?: never;
    path: {
        planId: string;
        itemId: string;
    };
    query?: never;
    url: '/api/forecast/plans/{planId}/items/{itemId}';
};

export type DeletePlannedItemResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeletePlannedItemResponse = DeletePlannedItemResponses[keyof DeletePlannedItemResponses];

export type GetPlannedItemData = {
    body?: never;
    path: {
        planId: string;
        itemId: string;
    };
    query?: never;
    url: '/api/forecast/plans/{planId}/items/{itemId}';
};

export type GetPlannedItemResponses = {
    /**
     * OK
     */
    200: PlannedItem;
};

export type GetPlannedItemResponse = GetPlannedItemResponses[keyof GetPlannedItemResponses];

export type UpdatePlannedItemData = {
    body: SimplePlannedItem;
    path: {
        planId: string;
        itemId: string;
    };
    query?: never;
    url: '/api/forecast/plans/{planId}/items/{itemId}';
};

export type UpdatePlannedItemResponses = {
    /**
     * OK
     */
    200: PlannedItem;
};

export type UpdatePlannedItemResponse = UpdatePlannedItemResponses[keyof UpdatePlannedItemResponses];

export type CreatePlannedItemData = {
    body: SimplePlannedItem;
    path: {
        planId: string;
    };
    query?: never;
    url: '/api/forecast/plans/{planId}/items';
};

export type CreatePlannedItemResponses = {
    /**
     * Created
     */
    201: PlannedItem;
};

export type CreatePlannedItemResponse = CreatePlannedItemResponses[keyof CreatePlannedItemResponses];

export type GetAllGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/groups';
};

export type GetAllGroupsResponses = {
    /**
     * OK
     */
    200: Array<Group>;
};

export type GetAllGroupsResponse = GetAllGroupsResponses[keyof GetAllGroupsResponses];

export type CreateGroupData = {
    body: CreateGroup;
    path?: never;
    query?: never;
    url: '/api/groups';
};

export type CreateGroupResponses = {
    /**
     * Created
     */
    201: Group;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type DeleteGroupData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type DeleteGroupResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type GetGroupData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type GetGroupResponses = {
    /**
     * OK
     */
    200: Group;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type UpdateGroupData = {
    body: Group;
    path?: never;
    query?: never;
    url: '/api/groups/{id}';
};

export type UpdateGroupResponses = {
    /**
     * OK
     */
    200: Group;
};

export type UpdateGroupResponse = UpdateGroupResponses[keyof UpdateGroupResponses];

export type GetAllInstitutionsData = {
    body?: never;
    path?: never;
    query?: {
        AccountType?: AccountType;
    };
    url: '/api/institutions';
};

export type GetAllInstitutionsResponses = {
    /**
     * OK
     */
    200: Array<Institution>;
};

export type GetAllInstitutionsResponse = GetAllInstitutionsResponses[keyof GetAllInstitutionsResponses];

export type CreateInstitutionData = {
    body: CreateInstitution;
    path?: never;
    query?: never;
    url: '/api/institutions';
};

export type CreateInstitutionResponses = {
    /**
     * Created
     */
    201: Institution;
};

export type CreateInstitutionResponse = CreateInstitutionResponses[keyof CreateInstitutionResponses];

export type GetInstitutionData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/institutions/{id}';
};

export type GetInstitutionResponses = {
    /**
     * OK
     */
    200: Institution;
};

export type GetInstitutionResponse = GetInstitutionResponses[keyof GetInstitutionResponses];

export type UpdateInstitutionData = {
    body: UpdateInstitution;
    path: {
        id: number;
    };
    query: {
        Name: string;
        InstitutionType: InstitutionType;
    };
    url: '/api/institutions/{id}';
};

export type UpdateInstitutionResponses = {
    /**
     * OK
     */
    200: Institution;
};

export type UpdateInstitutionResponse = UpdateInstitutionResponses[keyof UpdateInstitutionResponses];

export type GetFormattedInstrumentsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/instruments/summary';
};

export type GetFormattedInstrumentsListResponses = {
    /**
     * OK
     */
    200: InstrumentsList;
};

export type GetFormattedInstrumentsListResponse = GetFormattedInstrumentsListResponses[keyof GetFormattedInstrumentsListResponses];

export type GetInstrumentsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/instruments/list';
};

export type GetInstrumentsListResponses = {
    /**
     * OK
     */
    200: Array<ListItem>;
};

export type GetInstrumentsListResponse = GetInstrumentsListResponses[keyof GetInstrumentsListResponses];

export type ImportData = {
    body: {
        file: IFormFile;
    };
    path: {
        instrumentId: string;
        accountId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/accounts/{accountId}/import';
};

export type ImportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReprocessData = {
    body?: never;
    path: {
        instrumentId: string;
        accountId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/accounts/{accountId}/import/reprocess';
};

export type ReprocessResponses = {
    /**
     * No Content
     */
    204: void;
};

export type ReprocessResponse = ReprocessResponses[keyof ReprocessResponses];

export type GetAllInstrumentRulesData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules';
};

export type GetAllInstrumentRulesResponses = {
    /**
     * OK
     */
    200: Array<Rule>;
};

export type GetAllInstrumentRulesResponse = GetAllInstrumentRulesResponses[keyof GetAllInstrumentRulesResponses];

export type CreateInstrumentRuleData = {
    body: CreateRule;
    path?: never;
    query?: never;
    url: '/api/instruments/{instrumentId}/rules';
};

export type CreateInstrumentRuleResponses = {
    /**
     * OK
     */
    200: Rule;
    /**
     * Created
     */
    201: Rule;
};

export type CreateInstrumentRuleResponse = CreateInstrumentRuleResponses[keyof CreateInstrumentRuleResponses];

export type DeleteInstrumentRuleData = {
    body?: never;
    path: {
        instrumentId: string;
        ruleId: number;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules/{ruleId}';
};

export type DeleteInstrumentRuleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteInstrumentRuleResponse = DeleteInstrumentRuleResponses[keyof DeleteInstrumentRuleResponses];

export type GetInstrumentRuleData = {
    body?: never;
    path: {
        instrumentId: string;
        ruleId: number;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules/{ruleId}';
};

export type GetInstrumentRuleResponses = {
    /**
     * OK
     */
    200: Rule;
};

export type GetInstrumentRuleResponse = GetInstrumentRuleResponses[keyof GetInstrumentRuleResponses];

export type UpdateInstrumentRuleData = {
    body: UpdateRule;
    path: {
        instrumentId: string;
        ruleId: number;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules/{ruleId}';
};

export type UpdateInstrumentRuleResponses = {
    /**
     * OK
     */
    200: Rule;
};

export type UpdateInstrumentRuleResponse = UpdateInstrumentRuleResponses[keyof UpdateInstrumentRuleResponses];

export type RemoveTagFromInstrumentRuleData = {
    body?: never;
    path: {
        instrumentId: string;
        ruleId: number;
        tagId: number;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules/{ruleId}/tag/{tagId}';
};

export type RemoveTagFromInstrumentRuleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveTagFromInstrumentRuleResponse = RemoveTagFromInstrumentRuleResponses[keyof RemoveTagFromInstrumentRuleResponses];

export type AddTagToInstrumentRuleData = {
    body?: never;
    path: {
        instrumentId: string;
        ruleId: number;
        tagId: number;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules/{ruleId}/tag/{tagId}';
};

export type AddTagToInstrumentRuleResponses = {
    /**
     * OK
     */
    200: Rule;
};

export type AddTagToInstrumentRuleResponse = AddTagToInstrumentRuleResponses[keyof AddTagToInstrumentRuleResponses];

export type RunRulesData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/rules/run';
};

export type RunRulesResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetVirtualInstrumentsData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/virtual';
};

export type GetVirtualInstrumentsResponses = {
    /**
     * OK
     */
    200: Array<VirtualInstrument>;
};

export type GetVirtualInstrumentsResponse = GetVirtualInstrumentsResponses[keyof GetVirtualInstrumentsResponses];

export type CreateVirtualInstrumentData = {
    body: CreateVirtualInstrument;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/virtual';
};

export type CreateVirtualInstrumentResponses = {
    /**
     * Created
     */
    201: VirtualInstrument;
};

export type CreateVirtualInstrumentResponse = CreateVirtualInstrumentResponses[keyof CreateVirtualInstrumentResponses];

export type DeleteVirtualInstrumentData = {
    body?: never;
    path: {
        instrumentId: string;
        virtualInstrumentId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/virtual/{virtualInstrumentId}';
};

export type DeleteVirtualInstrumentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteVirtualInstrumentResponse = DeleteVirtualInstrumentResponses[keyof DeleteVirtualInstrumentResponses];

export type GetVirtualInstrumentData = {
    body?: never;
    path: {
        instrumentId: string;
        virtualInstrumentId: string;
    };
    query?: never;
    url: '/api/instruments/{instrumentId}/virtual/{virtualInstrumentId}';
};

export type GetVirtualInstrumentResponses = {
    /**
     * OK
     */
    200: VirtualInstrument;
};

export type GetVirtualInstrumentResponse = GetVirtualInstrumentResponses[keyof GetVirtualInstrumentResponses];

export type UpdateVirtualInstrumentData = {
    body: UpdateVirtualInstrument;
    path?: never;
    query?: never;
    url: '/api/instruments/{instrumentId}/virtual/{virtualInstrumentId}';
};

export type UpdateVirtualInstrumentResponses = {
    /**
     * OK
     */
    200: VirtualInstrument;
};

export type UpdateVirtualInstrumentResponse = UpdateVirtualInstrumentResponses[keyof UpdateVirtualInstrumentResponses];

export type UpdateVirtualInstrumentBalanceData = {
    body: UpdateBalance;
    path?: never;
    query?: never;
    url: '/api/instruments/{instrumentId}/virtual/{virtualInstrumentId}/balance';
};

export type UpdateVirtualInstrumentBalanceResponses = {
    /**
     * OK
     */
    200: VirtualInstrument;
};

export type UpdateVirtualInstrumentBalanceResponse = UpdateVirtualInstrumentBalanceResponses[keyof UpdateVirtualInstrumentBalanceResponses];

export type ImporterTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/reference-data/importer-types';
};

export type ImporterTypesResponses = {
    /**
     * OK
     */
    200: Array<ImporterType>;
};

export type ImporterTypesResponse = ImporterTypesResponses[keyof ImporterTypesResponses];

export type InOutReportData = {
    body?: never;
    path: {
        accountId: string;
        start: string;
        end: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/reports/in-out/{start}/{end}';
};

export type InOutReportResponses = {
    /**
     * OK
     */
    200: InOutReport;
};

export type InOutReportResponse = InOutReportResponses[keyof InOutReportResponses];

export type InOutTrendReportData = {
    body?: never;
    path: {
        accountId: string;
        start: string;
        end: string;
    };
    query: {
        Interval: ReportInterval;
    };
    url: '/api/accounts/{accountId}/reports/in-out-trend/{start}/{end}';
};

export type InOutTrendReportResponses = {
    /**
     * OK
     */
    200: InOutTrendReport;
};

export type InOutTrendReportResponse = InOutTrendReportResponses[keyof InOutTrendReportResponses];

export type InOutAverageReportData = {
    body?: never;
    path: {
        accountId: string;
        start: string;
        end: string;
    };
    query: {
        Interval: ReportInterval;
    };
    url: '/api/accounts/{accountId}/reports/in-out-average/{start}/{end}';
};

export type InOutAverageReportResponses = {
    /**
     * OK
     */
    200: InOutReport;
};

export type InOutAverageReportResponse = InOutAverageReportResponses[keyof InOutAverageReportResponses];

export type ByTagReportData = {
    body?: never;
    path: {
        reportType: ReportType;
        accountId: string;
        start: string;
        end: string;
    };
    query?: {
        ParentTagId?: number;
    };
    url: '/api/accounts/{accountId}/reports/{reportType}/tags/{start}/{end}';
};

export type ByTagReportResponses = {
    /**
     * OK
     */
    200: ByTagReport;
};

export type ByTagReportResponse = ByTagReportResponses[keyof ByTagReportResponses];

export type ByTagReportForTagData = {
    body?: never;
    path: {
        parentTagId: number;
        reportType: ReportType;
        accountId: string;
        start: string;
        end: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/reports/{reportType}/tags/{start}/{end}/{parentTagId}';
};

export type ByTagReportForTagResponses = {
    /**
     * OK
     */
    200: ByTagReport;
};

export type ByTagReportForTagResponse = ByTagReportForTagResponses[keyof ByTagReportForTagResponses];

export type TagBreakdownReportData = {
    body?: never;
    path: {
        reportType: ReportType;
        accountId: string;
        start: string;
        end: string;
    };
    query?: {
        ParentTagId?: number;
    };
    url: '/api/accounts/{accountId}/reports/{reportType}/breakdown/{start}/{end}';
};

export type TagBreakdownReportResponses = {
    /**
     * OK
     */
    200: BreakdownReport;
};

export type TagBreakdownReportResponse = TagBreakdownReportResponses[keyof TagBreakdownReportResponses];

export type TagBreakdownReportForTagData = {
    body?: never;
    path: {
        parentTagId: number;
        reportType: ReportType;
        accountId: string;
        start: string;
        end: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/reports/{reportType}/breakdown/{start}/{end}/{parentTagId}';
};

export type TagBreakdownReportForTagResponses = {
    /**
     * OK
     */
    200: BreakdownReport;
};

export type TagBreakdownReportForTagResponse = TagBreakdownReportForTagResponses[keyof TagBreakdownReportForTagResponses];

export type TagTrendReportData = {
    body?: never;
    path: {
        tagId: number;
        reportType: ReportType;
        accountId: string;
        start: string;
        end: string;
    };
    query?: {
        ApplySmoothing?: boolean;
    };
    url: '/api/accounts/{accountId}/reports/{reportType}/tag-trend/{start}/{end}/{tagId}';
};

export type TagTrendReportResponses = {
    /**
     * OK
     */
    200: TagTrendReport;
};

export type TagTrendReportResponse = TagTrendReportResponses[keyof TagTrendReportResponses];

export type AllTagAverageReportData = {
    body?: never;
    path: {
        reportType: ReportType;
        accountId: string;
        start: string;
        end: string;
    };
    query: {
        Top: number;
        Interval: ReportInterval;
    };
    url: '/api/accounts/{accountId}/reports/{reportType}/all-tag-average/{start}/{end}';
};

export type AllTagAverageReportResponses = {
    /**
     * OK
     */
    200: AllTagAverageReport;
};

export type AllTagAverageReportResponse = AllTagAverageReportResponses[keyof AllTagAverageReportResponses];

export type MonthlyBalancesReportData = {
    body?: never;
    path: {
        accountId: string;
    };
    query: {
        Start: string;
        End: string;
    };
    url: '/api/accounts/{accountId}/reports/monthly-balances';
};

export type MonthlyBalancesReportResponses = {
    /**
     * OK
     */
    200: MonthlyBalancesReport;
};

export type MonthlyBalancesReportResponse = MonthlyBalancesReportResponses[keyof MonthlyBalancesReportResponses];

export type MonthlyBalancesReportFromData = {
    body?: never;
    path: {
        accountId: string;
        start: string;
    };
    query: {
        End: string;
    };
    url: '/api/accounts/{accountId}/reports/monthly-balances/{start}';
};

export type MonthlyBalancesReportFromResponses = {
    /**
     * OK
     */
    200: MonthlyBalancesReport;
};

export type MonthlyBalancesReportFromResponse = MonthlyBalancesReportFromResponses[keyof MonthlyBalancesReportFromResponses];

export type MonthlyBalancesReportForPeriodData = {
    body?: never;
    path: {
        accountId: string;
        start: string;
        end: string;
    };
    query?: never;
    url: '/api/accounts/{accountId}/reports/monthly-balances/{start}/{end}';
};

export type MonthlyBalancesReportForPeriodResponses = {
    /**
     * OK
     */
    200: MonthlyBalancesReport;
};

export type MonthlyBalancesReportForPeriodResponse = MonthlyBalancesReportForPeriodResponses[keyof MonthlyBalancesReportForPeriodResponses];

export type GroupMonthlyBalancesReportData = {
    body?: never;
    path: {
        groupId: string;
        start: string;
        end: string;
    };
    query?: never;
    url: '/api/groups/{groupId}/reports/monthly-balances/{start}/{end}';
};

export type GroupMonthlyBalancesReportResponses = {
    /**
     * OK
     */
    200: MonthlyBalancesReport;
};

export type GroupMonthlyBalancesReportResponse = GroupMonthlyBalancesReportResponses[keyof GroupMonthlyBalancesReportResponses];

export type GetStockHoldingData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/stocks/{instrumentId}';
};

export type GetStockHoldingResponses = {
    /**
     * OK
     */
    200: StockHolding;
};

export type GetStockHoldingResponse = GetStockHoldingResponses[keyof GetStockHoldingResponses];

export type UpdateStockHoldingData = {
    body: UpdateStock;
    path?: never;
    query?: never;
    url: '/api/stocks/{instrumentId}';
};

export type UpdateStockHoldingResponses = {
    /**
     * OK
     */
    200: StockHolding;
};

export type UpdateStockHoldingResponse = UpdateStockHoldingResponses[keyof UpdateStockHoldingResponses];

export type GetStockHoldingCpiAdjustedGainLossData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/stocks/{instrumentId}/cpi-adjusted-gain-loss';
};

export type GetStockHoldingCpiAdjustedGainLossResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetStockHoldingCpiAdjustedGainLossResponse = GetStockHoldingCpiAdjustedGainLossResponses[keyof GetStockHoldingCpiAdjustedGainLossResponses];

export type CreateStockHoldingData = {
    body: CreateStock;
    path?: never;
    query?: never;
    url: '/api/stocks';
};

export type CreateStockHoldingResponses = {
    /**
     * Created
     */
    201: StockHolding;
};

export type CreateStockHoldingResponse = CreateStockHoldingResponses[keyof CreateStockHoldingResponses];

export type StockHoldingReportData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/stocks/{instrumentId}/reports/holding';
};

export type StockHoldingReportResponses = {
    /**
     * OK
     */
    200: StockHoldingReport;
};

export type StockHoldingReportResponse = StockHoldingReportResponses[keyof StockHoldingReportResponses];

export type StockValueReportData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query: {
        Start: string;
        End: string;
    };
    url: '/api/stocks/{instrumentId}/reports/value';
};

export type StockValueReportResponses = {
    /**
     * OK
     */
    200: StockValueReport;
};

export type StockValueReportResponse = StockValueReportResponses[keyof StockValueReportResponses];

export type GetStockTransactionsData = {
    body?: never;
    path: {
        instrumentId: string;
        pageSize: number;
        pageNumber: number;
    };
    query: {
        Filter?: string;
        Start?: string;
        End?: string;
        SortField?: string;
        SortDirection: SortDirection;
    };
    url: '/api/stocks/{instrumentId}/transactions/{pageSize}/{pageNumber}';
};

export type GetStockTransactionsResponses = {
    /**
     * OK
     */
    200: Array<StockTransaction>;
};

export type GetStockTransactionsResponse = GetStockTransactionsResponses[keyof GetStockTransactionsResponses];

export type CreateStockTransactionData = {
    body: CreateStockTransaction;
    path?: never;
    query?: never;
    url: '/api/stocks/{instrumentId}/transactions';
};

export type CreateStockTransactionResponses = {
    /**
     * OK
     */
    200: StockTransaction;
};

export type CreateStockTransactionResponse = CreateStockTransactionResponses[keyof CreateStockTransactionResponses];

export type GetTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tags';
};

export type GetTagsResponses = {
    /**
     * OK
     */
    200: Array<Tag>;
};

export type GetTagsResponse = GetTagsResponses[keyof GetTagsResponses];

export type CreateTagData = {
    body: CreateTag;
    path?: never;
    query?: never;
    url: '/api/tags';
};

export type CreateTagResponses = {
    /**
     * Created
     */
    201: Tag;
};

export type CreateTagResponse = CreateTagResponses[keyof CreateTagResponses];

export type GetTagHierarchyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tags/hierarchy';
};

export type GetTagHierarchyResponses = {
    /**
     * OK
     */
    200: TagHierarchy;
};

export type GetTagHierarchyResponse = GetTagHierarchyResponses[keyof GetTagHierarchyResponses];

export type DeleteTagData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tags/{id}';
};

export type DeleteTagResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type GetTagData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tags/{id}';
};

export type GetTagResponses = {
    /**
     * OK
     */
    200: Tag;
};

export type GetTagResponse = GetTagResponses[keyof GetTagResponses];

export type UpdateTagData = {
    body: UpdateTag;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tags/{id}';
};

export type UpdateTagResponses = {
    /**
     * OK
     */
    200: Tag;
};

export type UpdateTagResponse = UpdateTagResponses[keyof UpdateTagResponses];

export type CreateTagByNameData = {
    body: CreateByName;
    path?: never;
    query?: never;
    url: '/api/tags/{name}';
};

export type CreateTagByNameResponses = {
    /**
     * Created
     */
    201: Tag;
};

export type CreateTagByNameResponse = CreateTagByNameResponses[keyof CreateTagByNameResponses];

export type RemoveSubTagData = {
    body?: never;
    path: {
        id: number;
        subTagId: number;
    };
    query?: never;
    url: '/api/tags/{id}/tags/{subTagId}';
};

export type RemoveSubTagResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveSubTagResponse = RemoveSubTagResponses[keyof RemoveSubTagResponses];

export type AddSubTagData = {
    body?: never;
    path: {
        id: number;
        subTagId: number;
    };
    query?: never;
    url: '/api/tags/{id}/tags/{subTagId}';
};

export type AddSubTagResponses = {
    /**
     * OK
     */
    200: Tag;
};

export type AddSubTagResponse = AddSubTagResponses[keyof AddSubTagResponses];

export type GetTransactionsData = {
    body?: never;
    path: {
        pageSize: number;
        pageNumber: number;
        /**
         * The ID of the instrument (account) to filter transactions for.
         */
        instrumentId: string;
    };
    query: {
        /**
         * The search filter string to apply to transaction descriptions or references.
         */
        Filter?: string;
        /**
         * The date and time to start filtering transactions from.
         */
        Start?: string;
        /**
         * The date and time to end filtering transactions at.
         */
        End?: string;
        /**
         * The integer IDs of the tags to filter by.
         */
        TagIds?: Array<number>;
        /**
         * The field to sort the results by.
         */
        SortField?: string;
        /**
         * The type of transactions to include.
         */
        TransactionType?: TransactionFilterType;
        /**
         * The direction to sort the results.
         */
        SortDirection: SortDirection;
        /**
         * Converts the 'untagged' route parameter to a boolean.
         */
        Untagged?: string;
        /**
         * Exclude transactions where the amount has been offset to zero.
         */
        ExcludeNetZero?: boolean;
    };
    url: '/api/accounts/{instrumentId}/transactions/{pageSize}/{pageNumber}';
};

export type GetTransactionsResponses = {
    /**
     * OK
     */
    200: Array<Transaction>;
};

export type GetTransactionsResponse = GetTransactionsResponses[keyof GetTransactionsResponses];

export type GetUntaggedTransactionsData = {
    body?: never;
    path: {
        pageSize: number;
        pageNumber: number;
        /**
         * The ID of the instrument (account) to filter transactions for.
         */
        instrumentId: string;
        /**
         * Converts the 'untagged' route parameter to a boolean.
         */
        untagged: string;
    };
    query: {
        /**
         * The search filter string to apply to transaction descriptions or references.
         */
        Filter?: string;
        /**
         * The date and time to start filtering transactions from.
         */
        Start?: string;
        /**
         * The date and time to end filtering transactions at.
         */
        End?: string;
        /**
         * The integer IDs of the tags to filter by.
         */
        TagIds?: Array<number>;
        /**
         * The field to sort the results by.
         */
        SortField?: string;
        /**
         * The type of transactions to include.
         */
        TransactionType?: TransactionFilterType;
        /**
         * The direction to sort the results.
         */
        SortDirection: SortDirection;
        /**
         * Exclude transactions where the amount has been offset to zero.
         */
        ExcludeNetZero?: boolean;
    };
    url: '/api/accounts/{instrumentId}/transactions/{untagged}/{pageSize}/{pageNumber}';
};

export type GetUntaggedTransactionsResponses = {
    /**
     * OK
     */
    200: Array<Transaction>;
};

export type GetUntaggedTransactionsResponse = GetUntaggedTransactionsResponses[keyof GetUntaggedTransactionsResponses];

export type SearchTransactionsData = {
    body?: never;
    path: {
        instrumentId: string;
    };
    query: {
        Start: string;
        TransactionType: TransactionType;
        TagIds: Array<number>;
    };
    url: '/api/accounts/{instrumentId}/transactions';
};

export type SearchTransactionsResponses = {
    /**
     * OK
     */
    200: Array<Transaction>;
};

export type SearchTransactionsResponse = SearchTransactionsResponses[keyof SearchTransactionsResponses];

export type CreateTransactionData = {
    body: CreateTransaction;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}/transactions';
};

export type CreateTransactionResponses = {
    /**
     * OK
     */
    200: Transaction;
};

export type CreateTransactionResponse = CreateTransactionResponses[keyof CreateTransactionResponses];

export type SetBalanceData = {
    body: CreateTransaction;
    path: {
        instrumentId: string;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}/transactions/balance-adjustment';
};

export type SetBalanceResponses = {
    /**
     * OK
     */
    200: Transaction;
};

export type SetBalanceResponse = SetBalanceResponses[keyof SetBalanceResponses];

export type UpdateTransactionData = {
    body: UpdateTransaction;
    path?: never;
    query?: never;
    url: '/api/accounts/{instrumentId}/transactions/{id}';
};

export type UpdateTransactionResponses = {
    /**
     * OK
     */
    200: Transaction;
};

export type UpdateTransactionResponse = UpdateTransactionResponses[keyof UpdateTransactionResponses];

export type RemoveTagData = {
    body?: never;
    path: {
        instrumentId: string;
        id: string;
        tagId: number;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}/transactions/{id}/tag/{tagId}';
};

export type RemoveTagResponses = {
    /**
     * OK
     */
    200: Transaction;
};

export type RemoveTagResponse = RemoveTagResponses[keyof RemoveTagResponses];

export type AddTagData = {
    body?: never;
    path: {
        instrumentId: string;
        id: string;
        tagId: number;
    };
    query?: never;
    url: '/api/accounts/{instrumentId}/transactions/{id}/tag/{tagId}';
};

export type AddTagResponses = {
    /**
     * OK
     */
    200: Transaction;
};

export type AddTagResponse = AddTagResponses[keyof AddTagResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetUserResponses = {
    /**
     * OK
     */
    200: UserWithCards;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UpdateUser;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: UserWithCards;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];
