/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ProfileRouteImport } from "./routes/profile"
import { Route as SplatRouteImport } from "./routes/$"
import { Route as SettingsRouteRouteImport } from "./routes/settings/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TagsIndexRouteImport } from "./routes/tags/index"
import { Route as SettingsIndexRouteImport } from "./routes/settings/index"
import { Route as GroupsIndexRouteImport } from "./routes/groups/index"
import { Route as ForecastIndexRouteImport } from "./routes/forecast/index"
import { Route as FamilyIndexRouteImport } from "./routes/family/index"
import { Route as BudgetIndexRouteImport } from "./routes/budget/index"
import { Route as BillsIndexRouteImport } from "./routes/bills/index"
import { Route as AccountsIndexRouteImport } from "./routes/accounts/index"
import { Route as TagsVisualiserRouteImport } from "./routes/tags/visualiser"
import { Route as SharesCreateRouteImport } from "./routes/shares/create"
import { Route as GroupsCreateRouteImport } from "./routes/groups/create"
import { Route as BillsIdRouteImport } from "./routes/bills/$id"
import { Route as AssetsCreateRouteImport } from "./routes/assets/create"
import { Route as AccountsCreateRouteImport } from "./routes/accounts/create"
import { Route as SharesIdRouteRouteImport } from "./routes/shares/$id/route"
import { Route as AssetsIdRouteRouteImport } from "./routes/assets/$id/route"
import { Route as AccountsIdRouteRouteImport } from "./routes/accounts/$id/route"
import { Route as SharesIdIndexRouteImport } from "./routes/shares/$id/index"
import { Route as SettingsInstitutionsIndexRouteImport } from "./routes/settings/institutions/index"
import { Route as SettingsFamiliesIndexRouteImport } from "./routes/settings/families/index"
import { Route as BudgetReportIndexRouteImport } from "./routes/budget/report/index"
import { Route as BillsAccountsIndexRouteImport } from "./routes/bills/accounts/index"
import { Route as AssetsIdIndexRouteImport } from "./routes/assets/$id/index"
import { Route as AccountsIdIndexRouteImport } from "./routes/accounts/$id/index"
import { Route as SharesIdManageRouteImport } from "./routes/shares/$id/manage"
import { Route as SettingsInstitutionsAddRouteImport } from "./routes/settings/institutions/add"
import { Route as SettingsInstitutionsIdRouteImport } from "./routes/settings/institutions/$id"
import { Route as SettingsFamiliesAddRouteImport } from "./routes/settings/families/add"
import { Route as SettingsFamiliesIdRouteImport } from "./routes/settings/families/$id"
import { Route as GroupsIdManageRouteImport } from "./routes/groups/$id/manage"
import { Route as BillsAccountsCreateRouteImport } from "./routes/bills/accounts/create"
import { Route as BillsAccountsIdRouteImport } from "./routes/bills/accounts/$id"
import { Route as AssetsIdManageRouteImport } from "./routes/assets/$id/manage"
import { Route as AccountsIdTransactionsRouteImport } from "./routes/accounts/$id/transactions"
import { Route as AccountsIdRulesRouteImport } from "./routes/accounts/$id/rules"
import { Route as SharesIdReportsRouteRouteImport } from "./routes/shares/$id/reports/route"
import { Route as AccountsIdReportsRouteRouteImport } from "./routes/accounts/$id/reports/route"
import { Route as SharesIdTransactionsIndexRouteImport } from "./routes/shares/$id/transactions/index"
import { Route as SharesIdReportsIndexRouteImport } from "./routes/shares/$id/reports/index"
import { Route as BudgetReportYearIndexRouteImport } from "./routes/budget/report/$year/index"
import { Route as AccountsIdReportsIndexRouteImport } from "./routes/accounts/$id/reports/index"
import { Route as AccountsIdManageIndexRouteImport } from "./routes/accounts/$id/manage/index"
import { Route as SharesIdTransactionsAddRouteImport } from "./routes/shares/$id/transactions/add"
import { Route as SharesIdReportsValueRouteImport } from "./routes/shares/$id/reports/value"
import { Route as GroupsIdReportsMonthlyBalancesRouteImport } from "./routes/groups/$id/reports.monthly-balances"
import { Route as BudgetReportYearMonthRouteImport } from "./routes/budget/report/$year/$month"
import { Route as AccountsIdReportsMonthlyBalancesRouteImport } from "./routes/accounts/$id/reports/monthly-balances"
import { Route as AccountsIdReportsInOutRouteImport } from "./routes/accounts/$id/reports/in-out"
import { Route as AccountsIdReportsByTagRouteImport } from "./routes/accounts/$id/reports/by-tag"
import { Route as AccountsIdReportsAllTagAverageRouteImport } from "./routes/accounts/$id/reports/all-tag-average"
import { Route as AccountsIdVirtualVirtualIdRouteRouteImport } from "./routes/accounts/$id/virtual.$virtualId/route"
import { Route as AccountsIdVirtualVirtualIdIndexRouteImport } from "./routes/accounts/$id/virtual.$virtualId/index"
import { Route as AccountsIdReportsTagTrendIndexRouteImport } from "./routes/accounts/$id/reports/tag-trend/index"
import { Route as AccountsIdReportsBreakdownIndexRouteImport } from "./routes/accounts/$id/reports/breakdown/index"
import { Route as AccountsIdVirtualVirtualIdTransactionsRouteImport } from "./routes/accounts/$id/virtual.$virtualId/transactions"
import { Route as AccountsIdVirtualVirtualIdManageRouteImport } from "./routes/accounts/$id/virtual.$virtualId/manage"
import { Route as AccountsIdReportsTagTrendTagIdRouteImport } from "./routes/accounts/$id/reports/tag-trend/$tagId"
import { Route as AccountsIdReportsBreakdownTagIdRouteImport } from "./routes/accounts/$id/reports/breakdown/$tagId"
import { Route as AccountsIdManageVirtualCreateRouteImport } from "./routes/accounts/$id/manage/virtual.create"
import { Route as AccountsIdManageVirtualVirtualIdRouteImport } from "./routes/accounts/$id/manage/virtual.$virtualId"
import { Route as AccountsIdManageBankCreateRouteImport } from "./routes/accounts/$id/manage/bank.create"

const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: "/tags/",
  path: "/tags/",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: "/groups/",
  path: "/groups/",
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastIndexRoute = ForecastIndexRouteImport.update({
  id: "/forecast/",
  path: "/forecast/",
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyIndexRoute = FamilyIndexRouteImport.update({
  id: "/family/",
  path: "/family/",
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetIndexRoute = BudgetIndexRouteImport.update({
  id: "/budget/",
  path: "/budget/",
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIndexRoute = BillsIndexRouteImport.update({
  id: "/bills/",
  path: "/bills/",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: "/accounts/",
  path: "/accounts/",
  getParentRoute: () => rootRouteImport,
} as any)
const TagsVisualiserRoute = TagsVisualiserRouteImport.update({
  id: "/tags/visualiser",
  path: "/tags/visualiser",
  getParentRoute: () => rootRouteImport,
} as any)
const SharesCreateRoute = SharesCreateRouteImport.update({
  id: "/shares/create",
  path: "/shares/create",
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsCreateRoute = GroupsCreateRouteImport.update({
  id: "/groups/create",
  path: "/groups/create",
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIdRoute = BillsIdRouteImport.update({
  id: "/bills/$id",
  path: "/bills/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsCreateRoute = AssetsCreateRouteImport.update({
  id: "/assets/create",
  path: "/assets/create",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsCreateRoute = AccountsCreateRouteImport.update({
  id: "/accounts/create",
  path: "/accounts/create",
  getParentRoute: () => rootRouteImport,
} as any)
const SharesIdRouteRoute = SharesIdRouteRouteImport.update({
  id: "/shares/$id",
  path: "/shares/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdRouteRoute = AssetsIdRouteRouteImport.update({
  id: "/assets/$id",
  path: "/assets/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRouteRoute = AccountsIdRouteRouteImport.update({
  id: "/accounts/$id",
  path: "/accounts/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const SharesIdIndexRoute = SharesIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SharesIdRouteRoute,
} as any)
const SettingsInstitutionsIndexRoute =
  SettingsInstitutionsIndexRouteImport.update({
    id: "/institutions/",
    path: "/institutions/",
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsFamiliesIndexRoute = SettingsFamiliesIndexRouteImport.update({
  id: "/families/",
  path: "/families/",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const BudgetReportIndexRoute = BudgetReportIndexRouteImport.update({
  id: "/budget/report/",
  path: "/budget/report/",
  getParentRoute: () => rootRouteImport,
} as any)
const BillsAccountsIndexRoute = BillsAccountsIndexRouteImport.update({
  id: "/bills/accounts/",
  path: "/bills/accounts/",
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdIndexRoute = AssetsIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AssetsIdRouteRoute,
} as any)
const AccountsIdIndexRoute = AccountsIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AccountsIdRouteRoute,
} as any)
const SharesIdManageRoute = SharesIdManageRouteImport.update({
  id: "/manage",
  path: "/manage",
  getParentRoute: () => SharesIdRouteRoute,
} as any)
const SettingsInstitutionsAddRoute = SettingsInstitutionsAddRouteImport.update({
  id: "/institutions/add",
  path: "/institutions/add",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsInstitutionsIdRoute = SettingsInstitutionsIdRouteImport.update({
  id: "/institutions/$id",
  path: "/institutions/$id",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsFamiliesAddRoute = SettingsFamiliesAddRouteImport.update({
  id: "/families/add",
  path: "/families/add",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsFamiliesIdRoute = SettingsFamiliesIdRouteImport.update({
  id: "/families/$id",
  path: "/families/$id",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const GroupsIdManageRoute = GroupsIdManageRouteImport.update({
  id: "/groups/$id/manage",
  path: "/groups/$id/manage",
  getParentRoute: () => rootRouteImport,
} as any)
const BillsAccountsCreateRoute = BillsAccountsCreateRouteImport.update({
  id: "/bills/accounts/create",
  path: "/bills/accounts/create",
  getParentRoute: () => rootRouteImport,
} as any)
const BillsAccountsIdRoute = BillsAccountsIdRouteImport.update({
  id: "/bills/accounts/$id",
  path: "/bills/accounts/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdManageRoute = AssetsIdManageRouteImport.update({
  id: "/manage",
  path: "/manage",
  getParentRoute: () => AssetsIdRouteRoute,
} as any)
const AccountsIdTransactionsRoute = AccountsIdTransactionsRouteImport.update({
  id: "/transactions",
  path: "/transactions",
  getParentRoute: () => AccountsIdRouteRoute,
} as any)
const AccountsIdRulesRoute = AccountsIdRulesRouteImport.update({
  id: "/rules",
  path: "/rules",
  getParentRoute: () => AccountsIdRouteRoute,
} as any)
const SharesIdReportsRouteRoute = SharesIdReportsRouteRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => SharesIdRouteRoute,
} as any)
const AccountsIdReportsRouteRoute = AccountsIdReportsRouteRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => AccountsIdRouteRoute,
} as any)
const SharesIdTransactionsIndexRoute =
  SharesIdTransactionsIndexRouteImport.update({
    id: "/transactions/",
    path: "/transactions/",
    getParentRoute: () => SharesIdRouteRoute,
  } as any)
const SharesIdReportsIndexRoute = SharesIdReportsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SharesIdReportsRouteRoute,
} as any)
const BudgetReportYearIndexRoute = BudgetReportYearIndexRouteImport.update({
  id: "/budget/report/$year/",
  path: "/budget/report/$year/",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdReportsIndexRoute = AccountsIdReportsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AccountsIdReportsRouteRoute,
} as any)
const AccountsIdManageIndexRoute = AccountsIdManageIndexRouteImport.update({
  id: "/manage/",
  path: "/manage/",
  getParentRoute: () => AccountsIdRouteRoute,
} as any)
const SharesIdTransactionsAddRoute = SharesIdTransactionsAddRouteImport.update({
  id: "/transactions/add",
  path: "/transactions/add",
  getParentRoute: () => SharesIdRouteRoute,
} as any)
const SharesIdReportsValueRoute = SharesIdReportsValueRouteImport.update({
  id: "/value",
  path: "/value",
  getParentRoute: () => SharesIdReportsRouteRoute,
} as any)
const GroupsIdReportsMonthlyBalancesRoute =
  GroupsIdReportsMonthlyBalancesRouteImport.update({
    id: "/groups/$id/reports/monthly-balances",
    path: "/groups/$id/reports/monthly-balances",
    getParentRoute: () => rootRouteImport,
  } as any)
const BudgetReportYearMonthRoute = BudgetReportYearMonthRouteImport.update({
  id: "/budget/report/$year/$month",
  path: "/budget/report/$year/$month",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdReportsMonthlyBalancesRoute =
  AccountsIdReportsMonthlyBalancesRouteImport.update({
    id: "/monthly-balances",
    path: "/monthly-balances",
    getParentRoute: () => AccountsIdReportsRouteRoute,
  } as any)
const AccountsIdReportsInOutRoute = AccountsIdReportsInOutRouteImport.update({
  id: "/in-out",
  path: "/in-out",
  getParentRoute: () => AccountsIdReportsRouteRoute,
} as any)
const AccountsIdReportsByTagRoute = AccountsIdReportsByTagRouteImport.update({
  id: "/by-tag",
  path: "/by-tag",
  getParentRoute: () => AccountsIdReportsRouteRoute,
} as any)
const AccountsIdReportsAllTagAverageRoute =
  AccountsIdReportsAllTagAverageRouteImport.update({
    id: "/all-tag-average",
    path: "/all-tag-average",
    getParentRoute: () => AccountsIdReportsRouteRoute,
  } as any)
const AccountsIdVirtualVirtualIdRouteRoute =
  AccountsIdVirtualVirtualIdRouteRouteImport.update({
    id: "/virtual/$virtualId",
    path: "/virtual/$virtualId",
    getParentRoute: () => AccountsIdRouteRoute,
  } as any)
const AccountsIdVirtualVirtualIdIndexRoute =
  AccountsIdVirtualVirtualIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AccountsIdVirtualVirtualIdRouteRoute,
  } as any)
const AccountsIdReportsTagTrendIndexRoute =
  AccountsIdReportsTagTrendIndexRouteImport.update({
    id: "/tag-trend/",
    path: "/tag-trend/",
    getParentRoute: () => AccountsIdReportsRouteRoute,
  } as any)
const AccountsIdReportsBreakdownIndexRoute =
  AccountsIdReportsBreakdownIndexRouteImport.update({
    id: "/breakdown/",
    path: "/breakdown/",
    getParentRoute: () => AccountsIdReportsRouteRoute,
  } as any)
const AccountsIdVirtualVirtualIdTransactionsRoute =
  AccountsIdVirtualVirtualIdTransactionsRouteImport.update({
    id: "/transactions",
    path: "/transactions",
    getParentRoute: () => AccountsIdVirtualVirtualIdRouteRoute,
  } as any)
const AccountsIdVirtualVirtualIdManageRoute =
  AccountsIdVirtualVirtualIdManageRouteImport.update({
    id: "/manage",
    path: "/manage",
    getParentRoute: () => AccountsIdVirtualVirtualIdRouteRoute,
  } as any)
const AccountsIdReportsTagTrendTagIdRoute =
  AccountsIdReportsTagTrendTagIdRouteImport.update({
    id: "/tag-trend/$tagId",
    path: "/tag-trend/$tagId",
    getParentRoute: () => AccountsIdReportsRouteRoute,
  } as any)
const AccountsIdReportsBreakdownTagIdRoute =
  AccountsIdReportsBreakdownTagIdRouteImport.update({
    id: "/breakdown/$tagId",
    path: "/breakdown/$tagId",
    getParentRoute: () => AccountsIdReportsRouteRoute,
  } as any)
const AccountsIdManageVirtualCreateRoute =
  AccountsIdManageVirtualCreateRouteImport.update({
    id: "/manage/virtual/create",
    path: "/manage/virtual/create",
    getParentRoute: () => AccountsIdRouteRoute,
  } as any)
const AccountsIdManageVirtualVirtualIdRoute =
  AccountsIdManageVirtualVirtualIdRouteImport.update({
    id: "/manage/virtual/$virtualId",
    path: "/manage/virtual/$virtualId",
    getParentRoute: () => AccountsIdRouteRoute,
  } as any)
const AccountsIdManageBankCreateRoute =
  AccountsIdManageBankCreateRouteImport.update({
    id: "/manage/bank/create",
    path: "/manage/bank/create",
    getParentRoute: () => AccountsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/settings": typeof SettingsRouteRouteWithChildren
  "/$": typeof SplatRoute
  "/profile": typeof ProfileRoute
  "/accounts/$id": typeof AccountsIdRouteRouteWithChildren
  "/assets/$id": typeof AssetsIdRouteRouteWithChildren
  "/shares/$id": typeof SharesIdRouteRouteWithChildren
  "/accounts/create": typeof AccountsCreateRoute
  "/assets/create": typeof AssetsCreateRoute
  "/bills/$id": typeof BillsIdRoute
  "/groups/create": typeof GroupsCreateRoute
  "/shares/create": typeof SharesCreateRoute
  "/tags/visualiser": typeof TagsVisualiserRoute
  "/accounts/": typeof AccountsIndexRoute
  "/bills/": typeof BillsIndexRoute
  "/budget/": typeof BudgetIndexRoute
  "/family/": typeof FamilyIndexRoute
  "/forecast/": typeof ForecastIndexRoute
  "/groups/": typeof GroupsIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/tags/": typeof TagsIndexRoute
  "/accounts/$id/reports": typeof AccountsIdReportsRouteRouteWithChildren
  "/shares/$id/reports": typeof SharesIdReportsRouteRouteWithChildren
  "/accounts/$id/rules": typeof AccountsIdRulesRoute
  "/accounts/$id/transactions": typeof AccountsIdTransactionsRoute
  "/assets/$id/manage": typeof AssetsIdManageRoute
  "/bills/accounts/$id": typeof BillsAccountsIdRoute
  "/bills/accounts/create": typeof BillsAccountsCreateRoute
  "/groups/$id/manage": typeof GroupsIdManageRoute
  "/settings/families/$id": typeof SettingsFamiliesIdRoute
  "/settings/families/add": typeof SettingsFamiliesAddRoute
  "/settings/institutions/$id": typeof SettingsInstitutionsIdRoute
  "/settings/institutions/add": typeof SettingsInstitutionsAddRoute
  "/shares/$id/manage": typeof SharesIdManageRoute
  "/accounts/$id/": typeof AccountsIdIndexRoute
  "/assets/$id/": typeof AssetsIdIndexRoute
  "/bills/accounts/": typeof BillsAccountsIndexRoute
  "/budget/report/": typeof BudgetReportIndexRoute
  "/settings/families/": typeof SettingsFamiliesIndexRoute
  "/settings/institutions/": typeof SettingsInstitutionsIndexRoute
  "/shares/$id/": typeof SharesIdIndexRoute
  "/accounts/$id/virtual/$virtualId": typeof AccountsIdVirtualVirtualIdRouteRouteWithChildren
  "/accounts/$id/reports/all-tag-average": typeof AccountsIdReportsAllTagAverageRoute
  "/accounts/$id/reports/by-tag": typeof AccountsIdReportsByTagRoute
  "/accounts/$id/reports/in-out": typeof AccountsIdReportsInOutRoute
  "/accounts/$id/reports/monthly-balances": typeof AccountsIdReportsMonthlyBalancesRoute
  "/budget/report/$year/$month": typeof BudgetReportYearMonthRoute
  "/groups/$id/reports/monthly-balances": typeof GroupsIdReportsMonthlyBalancesRoute
  "/shares/$id/reports/value": typeof SharesIdReportsValueRoute
  "/shares/$id/transactions/add": typeof SharesIdTransactionsAddRoute
  "/accounts/$id/manage/": typeof AccountsIdManageIndexRoute
  "/accounts/$id/reports/": typeof AccountsIdReportsIndexRoute
  "/budget/report/$year/": typeof BudgetReportYearIndexRoute
  "/shares/$id/reports/": typeof SharesIdReportsIndexRoute
  "/shares/$id/transactions/": typeof SharesIdTransactionsIndexRoute
  "/accounts/$id/manage/bank/create": typeof AccountsIdManageBankCreateRoute
  "/accounts/$id/manage/virtual/$virtualId": typeof AccountsIdManageVirtualVirtualIdRoute
  "/accounts/$id/manage/virtual/create": typeof AccountsIdManageVirtualCreateRoute
  "/accounts/$id/reports/breakdown/$tagId": typeof AccountsIdReportsBreakdownTagIdRoute
  "/accounts/$id/reports/tag-trend/$tagId": typeof AccountsIdReportsTagTrendTagIdRoute
  "/accounts/$id/virtual/$virtualId/manage": typeof AccountsIdVirtualVirtualIdManageRoute
  "/accounts/$id/virtual/$virtualId/transactions": typeof AccountsIdVirtualVirtualIdTransactionsRoute
  "/accounts/$id/reports/breakdown/": typeof AccountsIdReportsBreakdownIndexRoute
  "/accounts/$id/reports/tag-trend/": typeof AccountsIdReportsTagTrendIndexRoute
  "/accounts/$id/virtual/$virtualId/": typeof AccountsIdVirtualVirtualIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/profile": typeof ProfileRoute
  "/accounts/create": typeof AccountsCreateRoute
  "/assets/create": typeof AssetsCreateRoute
  "/bills/$id": typeof BillsIdRoute
  "/groups/create": typeof GroupsCreateRoute
  "/shares/create": typeof SharesCreateRoute
  "/tags/visualiser": typeof TagsVisualiserRoute
  "/accounts": typeof AccountsIndexRoute
  "/bills": typeof BillsIndexRoute
  "/budget": typeof BudgetIndexRoute
  "/family": typeof FamilyIndexRoute
  "/forecast": typeof ForecastIndexRoute
  "/groups": typeof GroupsIndexRoute
  "/settings": typeof SettingsIndexRoute
  "/tags": typeof TagsIndexRoute
  "/accounts/$id/rules": typeof AccountsIdRulesRoute
  "/accounts/$id/transactions": typeof AccountsIdTransactionsRoute
  "/assets/$id/manage": typeof AssetsIdManageRoute
  "/bills/accounts/$id": typeof BillsAccountsIdRoute
  "/bills/accounts/create": typeof BillsAccountsCreateRoute
  "/groups/$id/manage": typeof GroupsIdManageRoute
  "/settings/families/$id": typeof SettingsFamiliesIdRoute
  "/settings/families/add": typeof SettingsFamiliesAddRoute
  "/settings/institutions/$id": typeof SettingsInstitutionsIdRoute
  "/settings/institutions/add": typeof SettingsInstitutionsAddRoute
  "/shares/$id/manage": typeof SharesIdManageRoute
  "/accounts/$id": typeof AccountsIdIndexRoute
  "/assets/$id": typeof AssetsIdIndexRoute
  "/bills/accounts": typeof BillsAccountsIndexRoute
  "/budget/report": typeof BudgetReportIndexRoute
  "/settings/families": typeof SettingsFamiliesIndexRoute
  "/settings/institutions": typeof SettingsInstitutionsIndexRoute
  "/shares/$id": typeof SharesIdIndexRoute
  "/accounts/$id/reports/all-tag-average": typeof AccountsIdReportsAllTagAverageRoute
  "/accounts/$id/reports/by-tag": typeof AccountsIdReportsByTagRoute
  "/accounts/$id/reports/in-out": typeof AccountsIdReportsInOutRoute
  "/accounts/$id/reports/monthly-balances": typeof AccountsIdReportsMonthlyBalancesRoute
  "/budget/report/$year/$month": typeof BudgetReportYearMonthRoute
  "/groups/$id/reports/monthly-balances": typeof GroupsIdReportsMonthlyBalancesRoute
  "/shares/$id/reports/value": typeof SharesIdReportsValueRoute
  "/shares/$id/transactions/add": typeof SharesIdTransactionsAddRoute
  "/accounts/$id/manage": typeof AccountsIdManageIndexRoute
  "/accounts/$id/reports": typeof AccountsIdReportsIndexRoute
  "/budget/report/$year": typeof BudgetReportYearIndexRoute
  "/shares/$id/reports": typeof SharesIdReportsIndexRoute
  "/shares/$id/transactions": typeof SharesIdTransactionsIndexRoute
  "/accounts/$id/manage/bank/create": typeof AccountsIdManageBankCreateRoute
  "/accounts/$id/manage/virtual/$virtualId": typeof AccountsIdManageVirtualVirtualIdRoute
  "/accounts/$id/manage/virtual/create": typeof AccountsIdManageVirtualCreateRoute
  "/accounts/$id/reports/breakdown/$tagId": typeof AccountsIdReportsBreakdownTagIdRoute
  "/accounts/$id/reports/tag-trend/$tagId": typeof AccountsIdReportsTagTrendTagIdRoute
  "/accounts/$id/virtual/$virtualId/manage": typeof AccountsIdVirtualVirtualIdManageRoute
  "/accounts/$id/virtual/$virtualId/transactions": typeof AccountsIdVirtualVirtualIdTransactionsRoute
  "/accounts/$id/reports/breakdown": typeof AccountsIdReportsBreakdownIndexRoute
  "/accounts/$id/reports/tag-trend": typeof AccountsIdReportsTagTrendIndexRoute
  "/accounts/$id/virtual/$virtualId": typeof AccountsIdVirtualVirtualIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/settings": typeof SettingsRouteRouteWithChildren
  "/$": typeof SplatRoute
  "/profile": typeof ProfileRoute
  "/accounts/$id": typeof AccountsIdRouteRouteWithChildren
  "/assets/$id": typeof AssetsIdRouteRouteWithChildren
  "/shares/$id": typeof SharesIdRouteRouteWithChildren
  "/accounts/create": typeof AccountsCreateRoute
  "/assets/create": typeof AssetsCreateRoute
  "/bills/$id": typeof BillsIdRoute
  "/groups/create": typeof GroupsCreateRoute
  "/shares/create": typeof SharesCreateRoute
  "/tags/visualiser": typeof TagsVisualiserRoute
  "/accounts/": typeof AccountsIndexRoute
  "/bills/": typeof BillsIndexRoute
  "/budget/": typeof BudgetIndexRoute
  "/family/": typeof FamilyIndexRoute
  "/forecast/": typeof ForecastIndexRoute
  "/groups/": typeof GroupsIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/tags/": typeof TagsIndexRoute
  "/accounts/$id/reports": typeof AccountsIdReportsRouteRouteWithChildren
  "/shares/$id/reports": typeof SharesIdReportsRouteRouteWithChildren
  "/accounts/$id/rules": typeof AccountsIdRulesRoute
  "/accounts/$id/transactions": typeof AccountsIdTransactionsRoute
  "/assets/$id/manage": typeof AssetsIdManageRoute
  "/bills/accounts/$id": typeof BillsAccountsIdRoute
  "/bills/accounts/create": typeof BillsAccountsCreateRoute
  "/groups/$id/manage": typeof GroupsIdManageRoute
  "/settings/families/$id": typeof SettingsFamiliesIdRoute
  "/settings/families/add": typeof SettingsFamiliesAddRoute
  "/settings/institutions/$id": typeof SettingsInstitutionsIdRoute
  "/settings/institutions/add": typeof SettingsInstitutionsAddRoute
  "/shares/$id/manage": typeof SharesIdManageRoute
  "/accounts/$id/": typeof AccountsIdIndexRoute
  "/assets/$id/": typeof AssetsIdIndexRoute
  "/bills/accounts/": typeof BillsAccountsIndexRoute
  "/budget/report/": typeof BudgetReportIndexRoute
  "/settings/families/": typeof SettingsFamiliesIndexRoute
  "/settings/institutions/": typeof SettingsInstitutionsIndexRoute
  "/shares/$id/": typeof SharesIdIndexRoute
  "/accounts/$id/virtual/$virtualId": typeof AccountsIdVirtualVirtualIdRouteRouteWithChildren
  "/accounts/$id/reports/all-tag-average": typeof AccountsIdReportsAllTagAverageRoute
  "/accounts/$id/reports/by-tag": typeof AccountsIdReportsByTagRoute
  "/accounts/$id/reports/in-out": typeof AccountsIdReportsInOutRoute
  "/accounts/$id/reports/monthly-balances": typeof AccountsIdReportsMonthlyBalancesRoute
  "/budget/report/$year/$month": typeof BudgetReportYearMonthRoute
  "/groups/$id/reports/monthly-balances": typeof GroupsIdReportsMonthlyBalancesRoute
  "/shares/$id/reports/value": typeof SharesIdReportsValueRoute
  "/shares/$id/transactions/add": typeof SharesIdTransactionsAddRoute
  "/accounts/$id/manage/": typeof AccountsIdManageIndexRoute
  "/accounts/$id/reports/": typeof AccountsIdReportsIndexRoute
  "/budget/report/$year/": typeof BudgetReportYearIndexRoute
  "/shares/$id/reports/": typeof SharesIdReportsIndexRoute
  "/shares/$id/transactions/": typeof SharesIdTransactionsIndexRoute
  "/accounts/$id/manage/bank/create": typeof AccountsIdManageBankCreateRoute
  "/accounts/$id/manage/virtual/$virtualId": typeof AccountsIdManageVirtualVirtualIdRoute
  "/accounts/$id/manage/virtual/create": typeof AccountsIdManageVirtualCreateRoute
  "/accounts/$id/reports/breakdown/$tagId": typeof AccountsIdReportsBreakdownTagIdRoute
  "/accounts/$id/reports/tag-trend/$tagId": typeof AccountsIdReportsTagTrendTagIdRoute
  "/accounts/$id/virtual/$virtualId/manage": typeof AccountsIdVirtualVirtualIdManageRoute
  "/accounts/$id/virtual/$virtualId/transactions": typeof AccountsIdVirtualVirtualIdTransactionsRoute
  "/accounts/$id/reports/breakdown/": typeof AccountsIdReportsBreakdownIndexRoute
  "/accounts/$id/reports/tag-trend/": typeof AccountsIdReportsTagTrendIndexRoute
  "/accounts/$id/virtual/$virtualId/": typeof AccountsIdVirtualVirtualIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/settings"
    | "/$"
    | "/profile"
    | "/accounts/$id"
    | "/assets/$id"
    | "/shares/$id"
    | "/accounts/create"
    | "/assets/create"
    | "/bills/$id"
    | "/groups/create"
    | "/shares/create"
    | "/tags/visualiser"
    | "/accounts/"
    | "/bills/"
    | "/budget/"
    | "/family/"
    | "/forecast/"
    | "/groups/"
    | "/settings/"
    | "/tags/"
    | "/accounts/$id/reports"
    | "/shares/$id/reports"
    | "/accounts/$id/rules"
    | "/accounts/$id/transactions"
    | "/assets/$id/manage"
    | "/bills/accounts/$id"
    | "/bills/accounts/create"
    | "/groups/$id/manage"
    | "/settings/families/$id"
    | "/settings/families/add"
    | "/settings/institutions/$id"
    | "/settings/institutions/add"
    | "/shares/$id/manage"
    | "/accounts/$id/"
    | "/assets/$id/"
    | "/bills/accounts/"
    | "/budget/report/"
    | "/settings/families/"
    | "/settings/institutions/"
    | "/shares/$id/"
    | "/accounts/$id/virtual/$virtualId"
    | "/accounts/$id/reports/all-tag-average"
    | "/accounts/$id/reports/by-tag"
    | "/accounts/$id/reports/in-out"
    | "/accounts/$id/reports/monthly-balances"
    | "/budget/report/$year/$month"
    | "/groups/$id/reports/monthly-balances"
    | "/shares/$id/reports/value"
    | "/shares/$id/transactions/add"
    | "/accounts/$id/manage/"
    | "/accounts/$id/reports/"
    | "/budget/report/$year/"
    | "/shares/$id/reports/"
    | "/shares/$id/transactions/"
    | "/accounts/$id/manage/bank/create"
    | "/accounts/$id/manage/virtual/$virtualId"
    | "/accounts/$id/manage/virtual/create"
    | "/accounts/$id/reports/breakdown/$tagId"
    | "/accounts/$id/reports/tag-trend/$tagId"
    | "/accounts/$id/virtual/$virtualId/manage"
    | "/accounts/$id/virtual/$virtualId/transactions"
    | "/accounts/$id/reports/breakdown/"
    | "/accounts/$id/reports/tag-trend/"
    | "/accounts/$id/virtual/$virtualId/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/$"
    | "/profile"
    | "/accounts/create"
    | "/assets/create"
    | "/bills/$id"
    | "/groups/create"
    | "/shares/create"
    | "/tags/visualiser"
    | "/accounts"
    | "/bills"
    | "/budget"
    | "/family"
    | "/forecast"
    | "/groups"
    | "/settings"
    | "/tags"
    | "/accounts/$id/rules"
    | "/accounts/$id/transactions"
    | "/assets/$id/manage"
    | "/bills/accounts/$id"
    | "/bills/accounts/create"
    | "/groups/$id/manage"
    | "/settings/families/$id"
    | "/settings/families/add"
    | "/settings/institutions/$id"
    | "/settings/institutions/add"
    | "/shares/$id/manage"
    | "/accounts/$id"
    | "/assets/$id"
    | "/bills/accounts"
    | "/budget/report"
    | "/settings/families"
    | "/settings/institutions"
    | "/shares/$id"
    | "/accounts/$id/reports/all-tag-average"
    | "/accounts/$id/reports/by-tag"
    | "/accounts/$id/reports/in-out"
    | "/accounts/$id/reports/monthly-balances"
    | "/budget/report/$year/$month"
    | "/groups/$id/reports/monthly-balances"
    | "/shares/$id/reports/value"
    | "/shares/$id/transactions/add"
    | "/accounts/$id/manage"
    | "/accounts/$id/reports"
    | "/budget/report/$year"
    | "/shares/$id/reports"
    | "/shares/$id/transactions"
    | "/accounts/$id/manage/bank/create"
    | "/accounts/$id/manage/virtual/$virtualId"
    | "/accounts/$id/manage/virtual/create"
    | "/accounts/$id/reports/breakdown/$tagId"
    | "/accounts/$id/reports/tag-trend/$tagId"
    | "/accounts/$id/virtual/$virtualId/manage"
    | "/accounts/$id/virtual/$virtualId/transactions"
    | "/accounts/$id/reports/breakdown"
    | "/accounts/$id/reports/tag-trend"
    | "/accounts/$id/virtual/$virtualId"
  id:
    | "__root__"
    | "/"
    | "/settings"
    | "/$"
    | "/profile"
    | "/accounts/$id"
    | "/assets/$id"
    | "/shares/$id"
    | "/accounts/create"
    | "/assets/create"
    | "/bills/$id"
    | "/groups/create"
    | "/shares/create"
    | "/tags/visualiser"
    | "/accounts/"
    | "/bills/"
    | "/budget/"
    | "/family/"
    | "/forecast/"
    | "/groups/"
    | "/settings/"
    | "/tags/"
    | "/accounts/$id/reports"
    | "/shares/$id/reports"
    | "/accounts/$id/rules"
    | "/accounts/$id/transactions"
    | "/assets/$id/manage"
    | "/bills/accounts/$id"
    | "/bills/accounts/create"
    | "/groups/$id/manage"
    | "/settings/families/$id"
    | "/settings/families/add"
    | "/settings/institutions/$id"
    | "/settings/institutions/add"
    | "/shares/$id/manage"
    | "/accounts/$id/"
    | "/assets/$id/"
    | "/bills/accounts/"
    | "/budget/report/"
    | "/settings/families/"
    | "/settings/institutions/"
    | "/shares/$id/"
    | "/accounts/$id/virtual/$virtualId"
    | "/accounts/$id/reports/all-tag-average"
    | "/accounts/$id/reports/by-tag"
    | "/accounts/$id/reports/in-out"
    | "/accounts/$id/reports/monthly-balances"
    | "/budget/report/$year/$month"
    | "/groups/$id/reports/monthly-balances"
    | "/shares/$id/reports/value"
    | "/shares/$id/transactions/add"
    | "/accounts/$id/manage/"
    | "/accounts/$id/reports/"
    | "/budget/report/$year/"
    | "/shares/$id/reports/"
    | "/shares/$id/transactions/"
    | "/accounts/$id/manage/bank/create"
    | "/accounts/$id/manage/virtual/$virtualId"
    | "/accounts/$id/manage/virtual/create"
    | "/accounts/$id/reports/breakdown/$tagId"
    | "/accounts/$id/reports/tag-trend/$tagId"
    | "/accounts/$id/virtual/$virtualId/manage"
    | "/accounts/$id/virtual/$virtualId/transactions"
    | "/accounts/$id/reports/breakdown/"
    | "/accounts/$id/reports/tag-trend/"
    | "/accounts/$id/virtual/$virtualId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  ProfileRoute: typeof ProfileRoute
  AccountsIdRouteRoute: typeof AccountsIdRouteRouteWithChildren
  AssetsIdRouteRoute: typeof AssetsIdRouteRouteWithChildren
  SharesIdRouteRoute: typeof SharesIdRouteRouteWithChildren
  AccountsCreateRoute: typeof AccountsCreateRoute
  AssetsCreateRoute: typeof AssetsCreateRoute
  BillsIdRoute: typeof BillsIdRoute
  GroupsCreateRoute: typeof GroupsCreateRoute
  SharesCreateRoute: typeof SharesCreateRoute
  TagsVisualiserRoute: typeof TagsVisualiserRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  BillsIndexRoute: typeof BillsIndexRoute
  BudgetIndexRoute: typeof BudgetIndexRoute
  FamilyIndexRoute: typeof FamilyIndexRoute
  ForecastIndexRoute: typeof ForecastIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  BillsAccountsIdRoute: typeof BillsAccountsIdRoute
  BillsAccountsCreateRoute: typeof BillsAccountsCreateRoute
  GroupsIdManageRoute: typeof GroupsIdManageRoute
  BillsAccountsIndexRoute: typeof BillsAccountsIndexRoute
  BudgetReportIndexRoute: typeof BudgetReportIndexRoute
  BudgetReportYearMonthRoute: typeof BudgetReportYearMonthRoute
  GroupsIdReportsMonthlyBalancesRoute: typeof GroupsIdReportsMonthlyBalancesRoute
  BudgetReportYearIndexRoute: typeof BudgetReportYearIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/profile": {
      id: "/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$": {
      id: "/$"
      path: "/$"
      fullPath: "/$"
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tags/": {
      id: "/tags/"
      path: "/tags"
      fullPath: "/tags/"
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/": {
      id: "/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/groups/": {
      id: "/groups/"
      path: "/groups"
      fullPath: "/groups/"
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forecast/": {
      id: "/forecast/"
      path: "/forecast"
      fullPath: "/forecast/"
      preLoaderRoute: typeof ForecastIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/family/": {
      id: "/family/"
      path: "/family"
      fullPath: "/family/"
      preLoaderRoute: typeof FamilyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/budget/": {
      id: "/budget/"
      path: "/budget"
      fullPath: "/budget/"
      preLoaderRoute: typeof BudgetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bills/": {
      id: "/bills/"
      path: "/bills"
      fullPath: "/bills/"
      preLoaderRoute: typeof BillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/accounts/": {
      id: "/accounts/"
      path: "/accounts"
      fullPath: "/accounts/"
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tags/visualiser": {
      id: "/tags/visualiser"
      path: "/tags/visualiser"
      fullPath: "/tags/visualiser"
      preLoaderRoute: typeof TagsVisualiserRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/shares/create": {
      id: "/shares/create"
      path: "/shares/create"
      fullPath: "/shares/create"
      preLoaderRoute: typeof SharesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/groups/create": {
      id: "/groups/create"
      path: "/groups/create"
      fullPath: "/groups/create"
      preLoaderRoute: typeof GroupsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bills/$id": {
      id: "/bills/$id"
      path: "/bills/$id"
      fullPath: "/bills/$id"
      preLoaderRoute: typeof BillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/assets/create": {
      id: "/assets/create"
      path: "/assets/create"
      fullPath: "/assets/create"
      preLoaderRoute: typeof AssetsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/accounts/create": {
      id: "/accounts/create"
      path: "/accounts/create"
      fullPath: "/accounts/create"
      preLoaderRoute: typeof AccountsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/shares/$id": {
      id: "/shares/$id"
      path: "/shares/$id"
      fullPath: "/shares/$id"
      preLoaderRoute: typeof SharesIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/assets/$id": {
      id: "/assets/$id"
      path: "/assets/$id"
      fullPath: "/assets/$id"
      preLoaderRoute: typeof AssetsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/accounts/$id": {
      id: "/accounts/$id"
      path: "/accounts/$id"
      fullPath: "/accounts/$id"
      preLoaderRoute: typeof AccountsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/shares/$id/": {
      id: "/shares/$id/"
      path: "/"
      fullPath: "/shares/$id/"
      preLoaderRoute: typeof SharesIdIndexRouteImport
      parentRoute: typeof SharesIdRouteRoute
    }
    "/settings/institutions/": {
      id: "/settings/institutions/"
      path: "/institutions"
      fullPath: "/settings/institutions/"
      preLoaderRoute: typeof SettingsInstitutionsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/families/": {
      id: "/settings/families/"
      path: "/families"
      fullPath: "/settings/families/"
      preLoaderRoute: typeof SettingsFamiliesIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/budget/report/": {
      id: "/budget/report/"
      path: "/budget/report"
      fullPath: "/budget/report/"
      preLoaderRoute: typeof BudgetReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bills/accounts/": {
      id: "/bills/accounts/"
      path: "/bills/accounts"
      fullPath: "/bills/accounts/"
      preLoaderRoute: typeof BillsAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/assets/$id/": {
      id: "/assets/$id/"
      path: "/"
      fullPath: "/assets/$id/"
      preLoaderRoute: typeof AssetsIdIndexRouteImport
      parentRoute: typeof AssetsIdRouteRoute
    }
    "/accounts/$id/": {
      id: "/accounts/$id/"
      path: "/"
      fullPath: "/accounts/$id/"
      preLoaderRoute: typeof AccountsIdIndexRouteImport
      parentRoute: typeof AccountsIdRouteRoute
    }
    "/shares/$id/manage": {
      id: "/shares/$id/manage"
      path: "/manage"
      fullPath: "/shares/$id/manage"
      preLoaderRoute: typeof SharesIdManageRouteImport
      parentRoute: typeof SharesIdRouteRoute
    }
    "/settings/institutions/add": {
      id: "/settings/institutions/add"
      path: "/institutions/add"
      fullPath: "/settings/institutions/add"
      preLoaderRoute: typeof SettingsInstitutionsAddRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/institutions/$id": {
      id: "/settings/institutions/$id"
      path: "/institutions/$id"
      fullPath: "/settings/institutions/$id"
      preLoaderRoute: typeof SettingsInstitutionsIdRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/families/add": {
      id: "/settings/families/add"
      path: "/families/add"
      fullPath: "/settings/families/add"
      preLoaderRoute: typeof SettingsFamiliesAddRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/families/$id": {
      id: "/settings/families/$id"
      path: "/families/$id"
      fullPath: "/settings/families/$id"
      preLoaderRoute: typeof SettingsFamiliesIdRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/groups/$id/manage": {
      id: "/groups/$id/manage"
      path: "/groups/$id/manage"
      fullPath: "/groups/$id/manage"
      preLoaderRoute: typeof GroupsIdManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bills/accounts/create": {
      id: "/bills/accounts/create"
      path: "/bills/accounts/create"
      fullPath: "/bills/accounts/create"
      preLoaderRoute: typeof BillsAccountsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bills/accounts/$id": {
      id: "/bills/accounts/$id"
      path: "/bills/accounts/$id"
      fullPath: "/bills/accounts/$id"
      preLoaderRoute: typeof BillsAccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/assets/$id/manage": {
      id: "/assets/$id/manage"
      path: "/manage"
      fullPath: "/assets/$id/manage"
      preLoaderRoute: typeof AssetsIdManageRouteImport
      parentRoute: typeof AssetsIdRouteRoute
    }
    "/accounts/$id/transactions": {
      id: "/accounts/$id/transactions"
      path: "/transactions"
      fullPath: "/accounts/$id/transactions"
      preLoaderRoute: typeof AccountsIdTransactionsRouteImport
      parentRoute: typeof AccountsIdRouteRoute
    }
    "/accounts/$id/rules": {
      id: "/accounts/$id/rules"
      path: "/rules"
      fullPath: "/accounts/$id/rules"
      preLoaderRoute: typeof AccountsIdRulesRouteImport
      parentRoute: typeof AccountsIdRouteRoute
    }
    "/shares/$id/reports": {
      id: "/shares/$id/reports"
      path: "/reports"
      fullPath: "/shares/$id/reports"
      preLoaderRoute: typeof SharesIdReportsRouteRouteImport
      parentRoute: typeof SharesIdRouteRoute
    }
    "/accounts/$id/reports": {
      id: "/accounts/$id/reports"
      path: "/reports"
      fullPath: "/accounts/$id/reports"
      preLoaderRoute: typeof AccountsIdReportsRouteRouteImport
      parentRoute: typeof AccountsIdRouteRoute
    }
    "/shares/$id/transactions/": {
      id: "/shares/$id/transactions/"
      path: "/transactions"
      fullPath: "/shares/$id/transactions/"
      preLoaderRoute: typeof SharesIdTransactionsIndexRouteImport
      parentRoute: typeof SharesIdRouteRoute
    }
    "/shares/$id/reports/": {
      id: "/shares/$id/reports/"
      path: "/"
      fullPath: "/shares/$id/reports/"
      preLoaderRoute: typeof SharesIdReportsIndexRouteImport
      parentRoute: typeof SharesIdReportsRouteRoute
    }
    "/budget/report/$year/": {
      id: "/budget/report/$year/"
      path: "/budget/report/$year"
      fullPath: "/budget/report/$year/"
      preLoaderRoute: typeof BudgetReportYearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/accounts/$id/reports/": {
      id: "/accounts/$id/reports/"
      path: "/"
      fullPath: "/accounts/$id/reports/"
      preLoaderRoute: typeof AccountsIdReportsIndexRouteImport
      parentRoute: typeof AccountsIdReportsRouteRoute
    }
    "/accounts/$id/manage/": {
      id: "/accounts/$id/manage/"
      path: "/manage"
      fullPath: "/accounts/$id/manage/"
      preLoaderRoute: typeof AccountsIdManageIndexRouteImport
      parentRoute: typeof AccountsIdRouteRoute
    }
    "/shares/$id/transactions/add": {
      id: "/shares/$id/transactions/add"
      path: "/transactions/add"
      fullPath: "/shares/$id/transactions/add"
      preLoaderRoute: typeof SharesIdTransactionsAddRouteImport
      parentRoute: typeof SharesIdRouteRoute
    }
    "/shares/$id/reports/value": {
      id: "/shares/$id/reports/value"
      path: "/value"
      fullPath: "/shares/$id/reports/value"
      preLoaderRoute: typeof SharesIdReportsValueRouteImport
      parentRoute: typeof SharesIdReportsRouteRoute
    }
    "/groups/$id/reports/monthly-balances": {
      id: "/groups/$id/reports/monthly-balances"
      path: "/groups/$id/reports/monthly-balances"
      fullPath: "/groups/$id/reports/monthly-balances"
      preLoaderRoute: typeof GroupsIdReportsMonthlyBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/budget/report/$year/$month": {
      id: "/budget/report/$year/$month"
      path: "/budget/report/$year/$month"
      fullPath: "/budget/report/$year/$month"
      preLoaderRoute: typeof BudgetReportYearMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/accounts/$id/reports/monthly-balances": {
      id: "/accounts/$id/reports/monthly-balances"
      path: "/monthly-balances"
      fullPath: "/accounts/$id/reports/monthly-balances"
      preLoaderRoute: typeof AccountsIdReportsMonthlyBalancesRouteImport
      parentRoute: typeof AccountsIdReportsRouteRoute
    }
    "/accounts/$id/reports/in-out": {
      id: "/accounts/$id/reports/in-out"
      path: "/in-out"
      fullPath: "/accounts/$id/reports/in-out"
      preLoaderRoute: typeof AccountsIdReportsInOutRouteImport
      parentRoute: typeof AccountsIdReportsRouteRoute
    }
    "/accounts/$id/reports/by-tag": {
      id: "/accounts/$id/reports/by-tag"
      path: "/by-tag"
      fullPath: "/accounts/$id/reports/by-tag"
      preLoaderRoute: typeof AccountsIdReportsByTagRouteImport
      parentRoute: typeof AccountsIdReportsRouteRoute
    }
    "/accounts/$id/reports/all-tag-average": {
      id: "/accounts/$id/reports/all-tag-average"
      path: "/all-tag-average"
      fullPath: "/accounts/$id/reports/all-tag-average"
      preLoaderRoute: typeof AccountsIdReportsAllTagAverageRouteImport
      parentRoute: typeof AccountsIdReportsRouteRoute
    }
    "/accounts/$id/virtual/$virtualId": {
      id: "/accounts/$id/virtual/$virtualId"
      path: "/virtual/$virtualId"
      fullPath: "/accounts/$id/virtual/$virtualId"
      preLoaderRoute: typeof AccountsIdVirtualVirtualIdRouteRouteImport
      parentRoute: typeof AccountsIdRouteRoute
    }
    "/accounts/$id/virtual/$virtualId/": {
      id: "/accounts/$id/virtual/$virtualId/"
      path: "/"
      fullPath: "/accounts/$id/virtual/$virtualId/"
      preLoaderRoute: typeof AccountsIdVirtualVirtualIdIndexRouteImport
      parentRoute: typeof AccountsIdVirtualVirtualIdRouteRoute
    }
    "/accounts/$id/reports/tag-trend/": {
      id: "/accounts/$id/reports/tag-trend/"
      path: "/tag-trend"
      fullPath: "/accounts/$id/reports/tag-trend/"
      preLoaderRoute: typeof AccountsIdReportsTagTrendIndexRouteImport
      parentRoute: typeof AccountsIdReportsRouteRoute
    }
    "/accounts/$id/reports/breakdown/": {
      id: "/accounts/$id/reports/breakdown/"
      path: "/breakdown"
      fullPath: "/accounts/$id/reports/breakdown/"
      preLoaderRoute: typeof AccountsIdReportsBreakdownIndexRouteImport
      parentRoute: typeof AccountsIdReportsRouteRoute
    }
    "/accounts/$id/virtual/$virtualId/transactions": {
      id: "/accounts/$id/virtual/$virtualId/transactions"
      path: "/transactions"
      fullPath: "/accounts/$id/virtual/$virtualId/transactions"
      preLoaderRoute: typeof AccountsIdVirtualVirtualIdTransactionsRouteImport
      parentRoute: typeof AccountsIdVirtualVirtualIdRouteRoute
    }
    "/accounts/$id/virtual/$virtualId/manage": {
      id: "/accounts/$id/virtual/$virtualId/manage"
      path: "/manage"
      fullPath: "/accounts/$id/virtual/$virtualId/manage"
      preLoaderRoute: typeof AccountsIdVirtualVirtualIdManageRouteImport
      parentRoute: typeof AccountsIdVirtualVirtualIdRouteRoute
    }
    "/accounts/$id/reports/tag-trend/$tagId": {
      id: "/accounts/$id/reports/tag-trend/$tagId"
      path: "/tag-trend/$tagId"
      fullPath: "/accounts/$id/reports/tag-trend/$tagId"
      preLoaderRoute: typeof AccountsIdReportsTagTrendTagIdRouteImport
      parentRoute: typeof AccountsIdReportsRouteRoute
    }
    "/accounts/$id/reports/breakdown/$tagId": {
      id: "/accounts/$id/reports/breakdown/$tagId"
      path: "/breakdown/$tagId"
      fullPath: "/accounts/$id/reports/breakdown/$tagId"
      preLoaderRoute: typeof AccountsIdReportsBreakdownTagIdRouteImport
      parentRoute: typeof AccountsIdReportsRouteRoute
    }
    "/accounts/$id/manage/virtual/create": {
      id: "/accounts/$id/manage/virtual/create"
      path: "/manage/virtual/create"
      fullPath: "/accounts/$id/manage/virtual/create"
      preLoaderRoute: typeof AccountsIdManageVirtualCreateRouteImport
      parentRoute: typeof AccountsIdRouteRoute
    }
    "/accounts/$id/manage/virtual/$virtualId": {
      id: "/accounts/$id/manage/virtual/$virtualId"
      path: "/manage/virtual/$virtualId"
      fullPath: "/accounts/$id/manage/virtual/$virtualId"
      preLoaderRoute: typeof AccountsIdManageVirtualVirtualIdRouteImport
      parentRoute: typeof AccountsIdRouteRoute
    }
    "/accounts/$id/manage/bank/create": {
      id: "/accounts/$id/manage/bank/create"
      path: "/manage/bank/create"
      fullPath: "/accounts/$id/manage/bank/create"
      preLoaderRoute: typeof AccountsIdManageBankCreateRouteImport
      parentRoute: typeof AccountsIdRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsFamiliesIdRoute: typeof SettingsFamiliesIdRoute
  SettingsFamiliesAddRoute: typeof SettingsFamiliesAddRoute
  SettingsInstitutionsIdRoute: typeof SettingsInstitutionsIdRoute
  SettingsInstitutionsAddRoute: typeof SettingsInstitutionsAddRoute
  SettingsFamiliesIndexRoute: typeof SettingsFamiliesIndexRoute
  SettingsInstitutionsIndexRoute: typeof SettingsInstitutionsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsFamiliesIdRoute: SettingsFamiliesIdRoute,
  SettingsFamiliesAddRoute: SettingsFamiliesAddRoute,
  SettingsInstitutionsIdRoute: SettingsInstitutionsIdRoute,
  SettingsInstitutionsAddRoute: SettingsInstitutionsAddRoute,
  SettingsFamiliesIndexRoute: SettingsFamiliesIndexRoute,
  SettingsInstitutionsIndexRoute: SettingsInstitutionsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface AccountsIdReportsRouteRouteChildren {
  AccountsIdReportsAllTagAverageRoute: typeof AccountsIdReportsAllTagAverageRoute
  AccountsIdReportsByTagRoute: typeof AccountsIdReportsByTagRoute
  AccountsIdReportsInOutRoute: typeof AccountsIdReportsInOutRoute
  AccountsIdReportsMonthlyBalancesRoute: typeof AccountsIdReportsMonthlyBalancesRoute
  AccountsIdReportsIndexRoute: typeof AccountsIdReportsIndexRoute
  AccountsIdReportsBreakdownTagIdRoute: typeof AccountsIdReportsBreakdownTagIdRoute
  AccountsIdReportsTagTrendTagIdRoute: typeof AccountsIdReportsTagTrendTagIdRoute
  AccountsIdReportsBreakdownIndexRoute: typeof AccountsIdReportsBreakdownIndexRoute
  AccountsIdReportsTagTrendIndexRoute: typeof AccountsIdReportsTagTrendIndexRoute
}

const AccountsIdReportsRouteRouteChildren: AccountsIdReportsRouteRouteChildren =
  {
    AccountsIdReportsAllTagAverageRoute: AccountsIdReportsAllTagAverageRoute,
    AccountsIdReportsByTagRoute: AccountsIdReportsByTagRoute,
    AccountsIdReportsInOutRoute: AccountsIdReportsInOutRoute,
    AccountsIdReportsMonthlyBalancesRoute:
      AccountsIdReportsMonthlyBalancesRoute,
    AccountsIdReportsIndexRoute: AccountsIdReportsIndexRoute,
    AccountsIdReportsBreakdownTagIdRoute: AccountsIdReportsBreakdownTagIdRoute,
    AccountsIdReportsTagTrendTagIdRoute: AccountsIdReportsTagTrendTagIdRoute,
    AccountsIdReportsBreakdownIndexRoute: AccountsIdReportsBreakdownIndexRoute,
    AccountsIdReportsTagTrendIndexRoute: AccountsIdReportsTagTrendIndexRoute,
  }

const AccountsIdReportsRouteRouteWithChildren =
  AccountsIdReportsRouteRoute._addFileChildren(
    AccountsIdReportsRouteRouteChildren,
  )

interface AccountsIdVirtualVirtualIdRouteRouteChildren {
  AccountsIdVirtualVirtualIdManageRoute: typeof AccountsIdVirtualVirtualIdManageRoute
  AccountsIdVirtualVirtualIdTransactionsRoute: typeof AccountsIdVirtualVirtualIdTransactionsRoute
  AccountsIdVirtualVirtualIdIndexRoute: typeof AccountsIdVirtualVirtualIdIndexRoute
}

const AccountsIdVirtualVirtualIdRouteRouteChildren: AccountsIdVirtualVirtualIdRouteRouteChildren =
  {
    AccountsIdVirtualVirtualIdManageRoute:
      AccountsIdVirtualVirtualIdManageRoute,
    AccountsIdVirtualVirtualIdTransactionsRoute:
      AccountsIdVirtualVirtualIdTransactionsRoute,
    AccountsIdVirtualVirtualIdIndexRoute: AccountsIdVirtualVirtualIdIndexRoute,
  }

const AccountsIdVirtualVirtualIdRouteRouteWithChildren =
  AccountsIdVirtualVirtualIdRouteRoute._addFileChildren(
    AccountsIdVirtualVirtualIdRouteRouteChildren,
  )

interface AccountsIdRouteRouteChildren {
  AccountsIdReportsRouteRoute: typeof AccountsIdReportsRouteRouteWithChildren
  AccountsIdRulesRoute: typeof AccountsIdRulesRoute
  AccountsIdTransactionsRoute: typeof AccountsIdTransactionsRoute
  AccountsIdIndexRoute: typeof AccountsIdIndexRoute
  AccountsIdVirtualVirtualIdRouteRoute: typeof AccountsIdVirtualVirtualIdRouteRouteWithChildren
  AccountsIdManageIndexRoute: typeof AccountsIdManageIndexRoute
  AccountsIdManageBankCreateRoute: typeof AccountsIdManageBankCreateRoute
  AccountsIdManageVirtualVirtualIdRoute: typeof AccountsIdManageVirtualVirtualIdRoute
  AccountsIdManageVirtualCreateRoute: typeof AccountsIdManageVirtualCreateRoute
}

const AccountsIdRouteRouteChildren: AccountsIdRouteRouteChildren = {
  AccountsIdReportsRouteRoute: AccountsIdReportsRouteRouteWithChildren,
  AccountsIdRulesRoute: AccountsIdRulesRoute,
  AccountsIdTransactionsRoute: AccountsIdTransactionsRoute,
  AccountsIdIndexRoute: AccountsIdIndexRoute,
  AccountsIdVirtualVirtualIdRouteRoute:
    AccountsIdVirtualVirtualIdRouteRouteWithChildren,
  AccountsIdManageIndexRoute: AccountsIdManageIndexRoute,
  AccountsIdManageBankCreateRoute: AccountsIdManageBankCreateRoute,
  AccountsIdManageVirtualVirtualIdRoute: AccountsIdManageVirtualVirtualIdRoute,
  AccountsIdManageVirtualCreateRoute: AccountsIdManageVirtualCreateRoute,
}

const AccountsIdRouteRouteWithChildren = AccountsIdRouteRoute._addFileChildren(
  AccountsIdRouteRouteChildren,
)

interface AssetsIdRouteRouteChildren {
  AssetsIdManageRoute: typeof AssetsIdManageRoute
  AssetsIdIndexRoute: typeof AssetsIdIndexRoute
}

const AssetsIdRouteRouteChildren: AssetsIdRouteRouteChildren = {
  AssetsIdManageRoute: AssetsIdManageRoute,
  AssetsIdIndexRoute: AssetsIdIndexRoute,
}

const AssetsIdRouteRouteWithChildren = AssetsIdRouteRoute._addFileChildren(
  AssetsIdRouteRouteChildren,
)

interface SharesIdReportsRouteRouteChildren {
  SharesIdReportsValueRoute: typeof SharesIdReportsValueRoute
  SharesIdReportsIndexRoute: typeof SharesIdReportsIndexRoute
}

const SharesIdReportsRouteRouteChildren: SharesIdReportsRouteRouteChildren = {
  SharesIdReportsValueRoute: SharesIdReportsValueRoute,
  SharesIdReportsIndexRoute: SharesIdReportsIndexRoute,
}

const SharesIdReportsRouteRouteWithChildren =
  SharesIdReportsRouteRoute._addFileChildren(SharesIdReportsRouteRouteChildren)

interface SharesIdRouteRouteChildren {
  SharesIdReportsRouteRoute: typeof SharesIdReportsRouteRouteWithChildren
  SharesIdManageRoute: typeof SharesIdManageRoute
  SharesIdIndexRoute: typeof SharesIdIndexRoute
  SharesIdTransactionsAddRoute: typeof SharesIdTransactionsAddRoute
  SharesIdTransactionsIndexRoute: typeof SharesIdTransactionsIndexRoute
}

const SharesIdRouteRouteChildren: SharesIdRouteRouteChildren = {
  SharesIdReportsRouteRoute: SharesIdReportsRouteRouteWithChildren,
  SharesIdManageRoute: SharesIdManageRoute,
  SharesIdIndexRoute: SharesIdIndexRoute,
  SharesIdTransactionsAddRoute: SharesIdTransactionsAddRoute,
  SharesIdTransactionsIndexRoute: SharesIdTransactionsIndexRoute,
}

const SharesIdRouteRouteWithChildren = SharesIdRouteRoute._addFileChildren(
  SharesIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  ProfileRoute: ProfileRoute,
  AccountsIdRouteRoute: AccountsIdRouteRouteWithChildren,
  AssetsIdRouteRoute: AssetsIdRouteRouteWithChildren,
  SharesIdRouteRoute: SharesIdRouteRouteWithChildren,
  AccountsCreateRoute: AccountsCreateRoute,
  AssetsCreateRoute: AssetsCreateRoute,
  BillsIdRoute: BillsIdRoute,
  GroupsCreateRoute: GroupsCreateRoute,
  SharesCreateRoute: SharesCreateRoute,
  TagsVisualiserRoute: TagsVisualiserRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  BillsIndexRoute: BillsIndexRoute,
  BudgetIndexRoute: BudgetIndexRoute,
  FamilyIndexRoute: FamilyIndexRoute,
  ForecastIndexRoute: ForecastIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  BillsAccountsIdRoute: BillsAccountsIdRoute,
  BillsAccountsCreateRoute: BillsAccountsCreateRoute,
  GroupsIdManageRoute: GroupsIdManageRoute,
  BillsAccountsIndexRoute: BillsAccountsIndexRoute,
  BudgetReportIndexRoute: BudgetReportIndexRoute,
  BudgetReportYearMonthRoute: BudgetReportYearMonthRoute,
  GroupsIdReportsMonthlyBalancesRoute: GroupsIdReportsMonthlyBalancesRoute,
  BudgetReportYearIndexRoute: BudgetReportYearIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
