global using Asm.MooBank.Domain.Repositories;
global using Asm.MooBank.Models;
global using Asm.MooBank.Services;
global using Asm.MooBank.Web;
global using Asm.MooBank.Web.Models;
global using Asm.Web;
global using Asm.Web.Security;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
