name: Deploy
on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version number'
        required: true
    secrets:
      OCTOPUSAPIKEY:
        description: 'Octopus API Key'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v3
      with:
        version: latest
    - name: Create artifacts folder
      run: mkdir ${{ github.workspace }}/artifacts
    - name: Package
      env:
        OCTOPUS_URL: ${{ vars.OCTOPUSURL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUSAPIKEY }}
        OCTOPUS_SPACE: Default
      run: octopus package zip create --id Asm.MooBank.Web --version ${{ inputs.version }} --base-path ${{ github.workspace }}/publish --out-folder ${{ github.workspace }}/artifacts
    - name: Push packages
      uses: OctopusDeploy/push-package-action@v3
      with:
        api_key: ${{ secrets.OCTOPUSAPIKEY }}
        server: ${{ vars.OCTOPUSURL }}
        packages: " ${{ github.workspace }}/artifacts/Asm.MooBank.Web.${{ inputs.version }}.zip"
        space: 'Default'
    - name: Create release
      uses: OctopusDeploy/create-release-action@v3
      with:
        api_key: ${{ secrets.OCTOPUSAPIKEY }}
        server: ${{ vars.OCTOPUSURL }}
        release_number: ${{ inputs.version }}
        package_version: ${{ inputs.version }}
        git_ref: ${{ (github.ref_type == 'tag' && github.event.repository.default_branch ) || (github.head_ref || github.ref) }}
        git_commit: ${{ github.event.after || github.event.pull_request.head.sha }}
        space: 'Default'
        project: "MooBank"
        progress: false