import { EditColumn } from "@andrewmclachlan/moo-ds";
import { MonthSelector } from "components";
import { DeleteIcon } from "@andrewmclachlan/moo-ds";
import type { BudgetLine as BudgetLineModel } from "api/types.gen";
import { useDeleteBudgetLine } from "../-hooks/useDeleteBudgetLine";
import { useUpdateBudgetLine } from "../-hooks/useUpdateBudgetLine";

// Notes generated by "Generate from history" are prefixed with this marker.
const autoPrefix = "Auto:";

export const BudgetLine: React.FC<BudgetLineProps> = ({ year, budgetLine, colour }) => {

    const updateBudgetLine = useUpdateBudgetLine();
    const deleteBudgetLine = useDeleteBudgetLine();

    const onDelete = () => {
        deleteBudgetLine(year, budgetLine.id);
    }

    const isAuto = budgetLine.notes?.startsWith(autoPrefix) ?? false;

    return (
        <tr key={budgetLine.id}>
            <td>
                <span className="tag-chip">
                    <span className="tag-swatch" style={colour ? { backgroundColor: colour } : undefined} />
                    {budgetLine.name}
                </span>
            </td>
            <EditColumn className={isAuto ? "provenance" : undefined} value={budgetLine.notes} onChange={(v) => updateBudgetLine(year, { ...budgetLine, notes: v.value })} />
            <EditColumn className="amount" value={budgetLine.amount.toFixed(2).toString()} onChange={(v) => updateBudgetLine(year, { ...budgetLine, amount: Number(v.value) })} />
            <td><MonthSelector value={budgetLine.month} onChange={(v) => updateBudgetLine(year, { ...budgetLine, month: v })} /></td>
            <td className="row-action"><DeleteIcon onClick={onDelete} /></td>
        </tr>
    );
}

export interface BudgetLineProps {
    year: number;
    budgetLine: BudgetLineModel;
    colour?: string;
}
